// Instruction categories; each CPU supplies its own resources and costs.
schedule_class IntAlu { doc = "Integer arithmetic, logic and shifts"; }
schedule_class IntMul32 { doc = "32-bit integer multiplication"; }
schedule_class IntMul64 { doc = "64-bit integer multiplication"; }
schedule_class IntDiv32 { doc = "32-bit integer division and remainder"; }
schedule_class IntDiv64 { doc = "64-bit integer division and remainder"; }

schedule_class Address { doc = "Address formation"; }
schedule_class Branch { doc = "Conditional and unconditional branches"; }
schedule_class Call { doc = "Call transfer only, excluding the callee"; }
schedule_class Constant32 { doc = "Variable-length 32-bit constant materialization"; }
schedule_class Constant64 { doc = "Variable-length 64-bit constant materialization"; }
schedule_class Copy { doc = "Scalar register moves"; }
schedule_class FloatAdd { doc = "Floating-point addition and subtraction"; }
schedule_class FloatCompare { doc = "Floating-point comparisons"; }
schedule_class FloatComparePair { doc = "Floating-point comparison and boolean inversion"; }
schedule_class FloatConvert { doc = "Floating-point precision conversion"; }
schedule_class FloatDiv { doc = "Floating-point division"; }
schedule_class FloatMul { doc = "Floating-point multiplication"; }
schedule_class FloatSqrt { doc = "Floating-point square root"; }
schedule_class FloatToInt { doc = "Floating-point to integer conversion"; }
schedule_class IntPair { doc = "Two-instruction integer sequences"; }
schedule_class IntRotate { doc = "Four-instruction rotate expansion"; }
schedule_class IntToFloat { doc = "Integer to floating-point conversion"; }
schedule_class Load { doc = "Memory loads including address formation"; }
schedule_class Return { doc = "Return transfer"; }
schedule_class Select { doc = "Branch-based select expansion"; }
schedule_class Store { doc = "Memory stores including address formation"; }
schedule_class Trap { doc = "Trap instruction issue, excluding exception handling"; }
