//! Compile checked, logical text projections into direct parser/printer code.
//! Scanning and symbol resolution remain shared runtime primitives.
mod emit;
mod schema;

use std::fmt::Write;

use crate::Error;
use crate::generate::packing::Alternative;
use crate::model::Definitions;

pub(crate) struct Plan {
    entries: Vec<Entry>,
    alternatives: Vec<schema::Schema>,
}

struct Entry {
    schema: schema::Schema,
    alternative: Option<usize>,
}

impl Plan {
    pub(crate) fn prepare(
        defs: &Definitions,
        formats: &[usize],
        alternatives: &[Alternative],
        source: &str,
    ) -> Result<Self, Error> {
        let schemas = alternatives
            .iter()
            .map(|alt| schema::compile(&alt.op, &defs.storage.records, source, &defs.types))
            .collect::<Result<Vec<_>, _>>()?;
        let mut entries = Vec::new();
        for (op, format) in defs.ops.iter().zip(formats) {
            let schema = schema::compile(op, &defs.storage.records, source, &defs.types)?;
            let mut matching = alternatives
                .iter()
                .enumerate()
                .filter(|(_, alt)| alt.targets.contains(format));
            let alternative = matching.next();
            if matching.next().is_some() {
                return Err(Error::at(
                    source,
                    op.offset,
                    "multiple text alternatives need an explicit discriminator",
                ));
            }
            if let Some((index, alt)) = alternative {
                let alt_schema = &schemas[index];
                if !schema.named.is_empty()
                    || alt_schema.named.is_empty()
                    || !alt_schema
                        .named
                        .iter()
                        .any(|n| matches!(n.mode, schema::Mode::Required))
                {
                    return Err(Error::at(
                        source,
                        alt.op.offset,
                        "text alternative requires distinct, required named fields",
                    ));
                }
            }
            entries.push(Entry {
                schema,
                alternative: alternative.map(|(index, _)| index),
            });
        }
        Ok(Self {
            entries,
            alternatives: schemas,
        })
    }
}

pub(crate) fn generate(
    defs: &Definitions,
    formats: &[usize],
    alternatives: &[Alternative],
    plan: &Plan,
) -> (String, String) {
    let mut parser = String::from(
        "// @generated by veloc-opgen; edit the .ops definitions.\nimpl OperandParser<'_> {\nfn parse(&mut self, opcode: crate::Opcode, flags: crate::MemFlags, input: &mut Cursor<'_>, ty: Option<crate::Type>) -> core::result::Result<crate::InstDraft, ParseError> {\nlet _ = ty;\nmatch opcode {\n",
    );
    let mut printer = String::from(
        "// @generated by veloc-opgen; edit the .ops definitions.\nimpl InstPrinter<'_> {\nfn fmt_instruction_data(&self, f: &mut dyn core::fmt::Write, data: &crate::InstView<'_>, ty: Option<crate::Type>) -> core::fmt::Result {\nmatch data.opcode() {\n",
    );
    for ((op, &format), entry) in defs.ops.iter().zip(formats).zip(&plan.entries) {
        let format = &defs.storage.formats[format];
        let schema = &entry.schema;
        let alternative = entry
            .alternative
            .map(|index| (&alternatives[index], &plan.alternatives[index]));
        writeln!(parser, "crate::Opcode::{} => {{", op.name).unwrap();
        writeln!(printer, "crate::Opcode::{} => match data {{", op.name).unwrap();
        if let Some((alt, alt_schema)) = alternative {
            let alt_op = &alt.op;
            let alt_format = &alt.format;
            parser.push_str("if input.has_named() {\n");
            parser.push_str(&emit::parse(
                alt_op,
                alt_format,
                alt_schema,
                &defs.storage.records,
                format.arity,
                &op.name,
                &defs.data.rust,
            ));
            parser.push_str("} else {\n");
            printer.push_str(&emit::print(
                op,
                alt_op,
                alt_format,
                alt_schema,
                format.arity,
                &defs.data.rust,
            ));
        }
        parser.push_str(&emit::parse(
            op,
            format,
            schema,
            &defs.storage.records,
            None,
            &op.name,
            &defs.data.rust,
        ));
        if alternative.is_some() {
            parser.push_str("}\n");
        }
        parser.push_str("},\n");
        printer.push_str(&emit::print(op, op, format, schema, None, &defs.data.rust));
        printer.push_str("_ => Err(core::fmt::Error),\n},\n");
    }
    parser.push_str("}\n}\n}\n");
    printer.push_str("}\n}\n}\n");
    (parser, printer)
}
