//! Compile checked, logical text projections into direct parser/printer code.
//! Scanning and symbol resolution remain shared runtime primitives.
mod emit;
mod schema;

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::Error;
use crate::model::{Binding, Definitions, Op, Param, ParamKind, TypeDef, TypeList};
use crate::storage::{Alternative, FieldType, Format};

pub(crate) fn generate(defs: &Definitions, source: &str) -> Result<(String, String), Error> {
    let mut parser = String::from(
        "// @generated by veloc-opgen; edit the .ops definitions.\nimpl OperandParser<'_> {\nfn parse(&mut self, opcode: crate::Opcode, ty: Option<crate::Type>, flags: crate::MemFlags, text: &str) -> core::result::Result<crate::InstructionData, ParseError> {\nmatch opcode {\n",
    );
    let mut printer = String::from(
        "// @generated by veloc-opgen; edit the .ops definitions.\nimpl InstPrinter<'_> {\nfn fmt_instruction_data(&self, f: &mut dyn core::fmt::Write, data: &crate::InstructionData, ty: Option<crate::Type>) -> core::fmt::Result {\nmatch data.opcode() {\n",
    );
    for op in &defs.ops {
        let format = defs
            .storage
            .formats
            .iter()
            .find(|f| f.name == op.format)
            .expect("checked format");
        let schema = schema::compile(op, &defs.storage.records, source, &defs.types)?;
        let alternatives = defs
            .storage
            .alternatives
            .iter()
            .filter(|alt| alt.formats.contains(&op.format))
            .collect::<Vec<_>>();
        // Dispatch must be unambiguous without inspecting opcode-specific names.
        // More than one alternate needs a declared discriminator first.
        if alternatives.len() > 1 {
            return Err(Error::at(
                source,
                op.offset,
                "multiple text alternatives need an explicit discriminator",
            ));
        }
        writeln!(parser, "crate::Opcode::{} => {{", op.name).unwrap();
        writeln!(printer, "crate::Opcode::{} => match data {{", op.name).unwrap();
        for alt in alternatives {
            let (alt_op, alt_format) = alternate(op, alt, defs, source)?;
            let alt_schema = schema::compile(&alt_op, &defs.storage.records, source, &defs.types)?;
            if !schema.named.is_empty()
                || alt_schema.named.is_empty()
                || !alt_schema
                    .named
                    .iter()
                    .any(|n| matches!(n.mode, schema::Mode::Required))
            {
                return Err(Error::at(
                    source,
                    alt.text.offset,
                    "text alternative requires distinct, required named fields",
                ));
            }
            parser.push_str(
                "if split_top_level(text, ',').iter().any(|field| field.contains('=')) {\n",
            );
            parser.push_str(&emit::parse(
                &alt_op,
                &alt_format,
                &alt_schema,
                &defs.storage.records,
                format.arity,
            ));
            parser.push_str("} else {\n");
            printer.push_str(&emit::print(
                op,
                &alt_op,
                &alt_format,
                &alt_schema,
                format.arity,
            ));
        }
        parser.push_str(&emit::parse(
            op,
            format,
            &schema,
            &defs.storage.records,
            None,
        ));
        if defs
            .storage
            .alternatives
            .iter()
            .any(|alt| alt.formats.contains(&op.format))
        {
            parser.push_str("}\n");
        }
        parser.push_str("},\n");
        printer.push_str(&emit::print(op, op, format, &schema, None));
        printer.push_str("_ => Err(core::fmt::Error),\n},\n");
    }
    parser.push_str("}\n}\n}\n");
    printer.push_str("}\n}\n}\n");
    Ok((parser, printer))
}

/// An alternate storage layout exposes its own text-facing fields. Pool handles
/// become structured properties, while its primary list retains canonical arity.
fn alternate(
    op: &Op,
    alt: &Alternative,
    defs: &Definitions,
    source: &str,
) -> Result<(Op, Format), Error> {
    let mut params = Vec::new();
    let mut packing = BTreeMap::new();
    for field in &alt.fields {
        let FieldType::Named(ty) = &field.ty else {
            return Err(Error::at(
                source,
                alt.text.offset,
                "alternate text fields must use named storage types",
            ));
        };
        let (kind, binding) = match ty.as_str() {
            "Opcode" => continue,
            "Value" => (ParamKind::Value, Binding::Name(field.name.clone())),
            "ValueList" => (ParamKind::Values, Binding::Name(field.name.clone())),
            "BlockCall" => (ParamKind::Successor, Binding::Name(field.name.clone())),
            "ConstantPoolId" => (
                ParamKind::Property("Bytes".into()),
                Binding::Pool(field.name.clone()),
            ),
            _ => match defs.storage.records.iter().find(|r| r.storage == *ty) {
                Some(record) => (
                    ParamKind::Property(record.name.clone()),
                    Binding::Pool(field.name.clone()),
                ),
                None => (
                    ParamKind::Property(ty.clone()),
                    Binding::Name(field.name.clone()),
                ),
            },
        };
        params.push(Param {
            name: field.name.clone(),
            kind,
        });
        packing.insert(field.name.clone(), binding);
    }
    Ok((
        Op {
            offset: alt.text.offset,
            name: op.name.clone(),
            mnemonic: op.mnemonic.clone(),
            format: alt.name.clone(),
            signature: TypeDef {
                operands: TypeList::Fixed(Vec::new()),
                results: TypeList::Fixed(Vec::new()),
                relations: Vec::new(),
            },
            params,
            packing,
            signature_source: None,
            text: Some(alt.text.clone()),
            traits: Vec::new(),
            memory: "NONE".into(),
            constraints: Vec::new(),
            identity: None,
            absorbing: None,
            semantics: None,
        },
        Format {
            name: alt.name.clone(),
            arity: None,
            fixed_opcode: None,
            fields: alt.fields.clone(),
        },
    ))
}
