//! Compile checked, logical text projections into direct parser/printer code.
//! Scanning and symbol resolution remain shared runtime primitives.
mod emit;
mod schema;

use std::fmt::Write;

use crate::Error;
use crate::generate::packing::Alternative;
use crate::model::Definitions;

/// Only allocation, physical reads and the SSA-reference codec vary by host.
#[derive(Clone, Copy)]
pub(super) enum Host<'a> {
    Packed(&'a crate::storage::Format),
    Operands(&'a crate::storage::operands::Operands),
}

impl Host<'_> {
    fn value(self) -> String {
        match self {
            Self::Packed(_) => "crate::Value".into(),
            Self::Operands(storage) => storage.register_rust.clone(),
        }
    }

    fn prefix(self) -> &'static str {
        match self {
            Self::Packed(_) => "crate::inst::",
            Self::Operands(_) => "",
        }
    }
}

pub(crate) struct Plan {
    entries: Vec<Entry>,
    alternatives: Vec<schema::Schema>,
}

struct Entry {
    op: usize,
    schema: schema::Schema,
    alternative: Option<usize>,
}

impl Plan {
    pub(crate) fn prepare(
        defs: &Definitions,
        formats: &[usize],
        alternatives: &[Alternative],
        source: &str,
    ) -> Result<Self, Error> {
        let schemas = alternatives
            .iter()
            .map(|alt| schema::compile(&alt.op, &defs.data.records, source, &defs.types))
            .collect::<Result<Vec<_>, _>>()?;
        let mut entries = Vec::new();
        for (index, op) in defs.ops.iter().enumerate() {
            let format = formats.get(index);
            // An array host opts operations into its text frontend explicitly.
            if format.is_none() && op.text.is_none() {
                continue;
            }
            let schema = schema::compile(op, &defs.data.records, source, &defs.types)?;
            let mut matching = alternatives
                .iter()
                .enumerate()
                .filter(|(_, alt)| format.is_some_and(|format| alt.targets.contains(format)));
            let alternative = matching.next();
            if matching.next().is_some() {
                return Err(Error::at(
                    source,
                    op.offset,
                    "multiple text alternatives need an explicit discriminator",
                ));
            }
            if let Some((index, alt)) = alternative {
                let alt_schema = &schemas[index];
                if !schema.named.is_empty()
                    || alt_schema.named.is_empty()
                    || !alt_schema
                        .named
                        .iter()
                        .any(|n| matches!(n.mode, schema::Mode::Required))
                {
                    return Err(Error::at(
                        source,
                        alt.op.offset,
                        "text alternative requires distinct, required named fields",
                    ));
                }
            }
            entries.push(Entry {
                op: index,
                schema,
                alternative: alternative.map(|(index, _)| index),
            });
        }
        Ok(Self {
            entries,
            alternatives: schemas,
        })
    }
}

pub(crate) fn generate(
    defs: &Definitions,
    formats: &[usize],
    alternatives: &[Alternative],
    plan: &Plan,
) -> (String, String) {
    let mut parser = String::from(
        "// @generated by veloc-opgen; edit the .ops definitions.\nimpl OperandParser<'_> {\nfn parse(&mut self, opcode: crate::Opcode, flags: crate::MemFlags, input: &mut Cursor<'_>, ty: Option<crate::Type>) -> core::result::Result<crate::Inst, ParseError> {\nlet _ = ty;\nmatch opcode {\n",
    );
    let mut printer = String::from(
        "// @generated by veloc-opgen; edit the .ops definitions.\nimpl InstPrinter<'_> {\nfn fmt_instruction_data(&self, f: &mut dyn core::fmt::Write, data: &crate::InstView<'_>, ty: Option<crate::Type>) -> core::fmt::Result {\nmatch data.opcode() {\n",
    );
    for ((op, &format), entry) in defs.ops.iter().zip(formats).zip(&plan.entries) {
        let format = &defs.storage.formats[format];
        let schema = &entry.schema;
        let alternative = entry
            .alternative
            .map(|index| (&alternatives[index], &plan.alternatives[index]));
        writeln!(parser, "crate::Opcode::{} => {{", op.name).unwrap();
        writeln!(printer, "crate::Opcode::{} => match data {{", op.name).unwrap();
        if let Some((alt, alt_schema)) = alternative {
            let alt_op = &alt.op;
            let alt_format = &alt.format;
            parser.push_str("if input.has_named() {\n");
            parser.push_str(&emit::parse(
                alt_op,
                Host::Packed(alt_format),
                alt_schema,
                &defs.data.records,
                format.arity,
                &op.name,
                &defs.data.rust,
            ));
            parser.push_str("} else {\n");
            printer.push_str(&emit::print(
                op,
                alt_op,
                Host::Packed(alt_format),
                alt_schema,
                format.arity,
                &defs.data.rust,
            ));
        }
        parser.push_str(&emit::parse(
            op,
            Host::Packed(format),
            schema,
            &defs.data.records,
            None,
            &op.name,
            &defs.data.rust,
        ));
        if alternative.is_some() {
            parser.push_str("}\n");
        }
        parser.push_str("},\n");
        printer.push_str(&emit::print(
            op,
            op,
            Host::Packed(format),
            schema,
            None,
            &defs.data.rust,
        ));
        printer.push_str("_ => Err(core::fmt::Error),\n},\n");
    }
    parser.push_str("}\n}\n}\n");
    printer.push_str("}\n}\n}\n");
    (parser, printer)
}

/// Array-storage hosts implement the same token/atom protocol as packed hosts.
/// Results are supplied by the enclosing instruction parser, not text operands.
pub(crate) fn generate_operands(
    defs: &Definitions,
    storage: &crate::storage::operands::Operands,
    plan: &Plan,
) -> (String, String) {
    if plan.entries.is_empty() {
        return (String::new(), String::new());
    }
    let opcode = &storage.opcode;
    let register = &storage.register_rust;
    let reader = &storage.reader;
    let mut parser = format!(
        "impl OperandParser<'_> {{
        fn parse(&mut self, opcode: {opcode}, flags: crate::MemFlags, input: &mut Cursor<'_>, ty: Option<crate::Type>, results: &[{register}]) -> core::result::Result<crate::InstId, ParseError> {{
        let _ = ty;
        match opcode {{"
    );
    let mut printer = format!(
        "impl InstPrinter<'_> {{
        fn fmt_instruction_data<'a>(&self, f: &mut dyn core::fmt::Write, data: impl {reader}<'a>, ty: Option<crate::Type>) -> core::fmt::Result {{
        let _ = ty;
        match data.opcode() {{"
    );
    for entry in &plan.entries {
        let op = &defs.ops[entry.op];
        writeln!(parser, "{opcode}::{} => {{", op.name).unwrap();
        let layout = op.operands();
        let count = layout.counts[0];
        let cmp = if layout.tails[0] { "<" } else { "!=" };
        writeln!(parser, "if results.len() {cmp} {count} {{ return Err(input.error(\"invalid result count\")); }}").unwrap();
        parser.push_str(&emit::parse(
            op,
            Host::Operands(storage),
            &entry.schema,
            &defs.data.records,
            None,
            &op.name,
            &defs.data.rust,
        ));
        parser.push_str("},\n");
        writeln!(printer, "Some({opcode}::{}) => {{", op.name).unwrap();
        printer.push_str(&emit::print(
            op,
            op,
            Host::Operands(storage),
            &entry.schema,
            None,
            &defs.data.rust,
        ));
        printer.push_str("},\n");
    }
    if plan.entries.len() != defs.ops.len() {
        parser.push_str("_ => Err(input.error(\"operation has no text projection\")),\n");
    }
    parser.push_str("} } }\n");
    printer.push_str("_ => Err(core::fmt::Error),\n} } }\n");
    (parser, printer)
}
