//! Rust emission over an explicit host interface. The checked rule plan is
//! independent of source/target containers and is never interpreted at runtime.
use super::{Program, check::TypeRef, identifier};
use std::collections::BTreeMap;
use std::fmt::Write;
use veloc_opgen::Error;

/// Rust enum paths are provided by the consumer, never guessed from IR names.
pub struct Rust<'a> {
    pub function: &'a str,
    pub context: &'a str,
    pub source: (&'a str, &'a str),
    pub target: (&'a str, &'a str),
}

impl Program {
    pub fn rust(&self, config: Rust<'_>) -> Result<String, Error> {
        let Rust {
            function,
            context,
            source,
            target,
        } = config;
        if !identifier(function)
            || !identifier(context)
            || !source.1.split("::").all(identifier)
            || !target.1.split("::").all(identifier)
        {
            return Err(Error::at("", 0, "invalid Rust binding"));
        }
        let opcode = |name: &str, dialect: (&str, &str)| -> Result<String, Error> {
            let Some((namespace, name)) = name.split_once('.') else {
                return Err(Error::at("", 0, "missing operation namespace"));
            };
            if namespace != dialect.0 || !identifier(name) {
                return Err(Error::at(
                    "",
                    0,
                    format!("operation {namespace}.{name} has no Rust binding"),
                ));
            }
            Ok(format!("{}::{name}", dialect.1))
        };
        let mut code = format!(
            "// @generated by the typed ISLE rule compiler.\n\
             #[allow(dead_code)]\n\
             trait {context} {{\n\
             type Value: Copy;\n\
             type Type: Copy;\n\
             fn input(&self, index: usize) -> Self::Value;\n\
             fn result(&self, index: usize) -> Self::Value;\n\
             fn value_type(&self, value: Self::Value) -> Self::Type;\n\
             fn temp(&mut self, ty: Self::Type) -> Self::Value;\n\
             fn emit(&mut self, opcode: {}, results: &[Self::Value], inputs: &[Self::Value]);\n\
             fn bind(&mut self, result: usize, value: Self::Value);\n\
             }}\n\
             fn {function}<C: {context}>(opcode: {}, ctx: &mut C) -> bool {{\n\
             match opcode {{\n",
            target.1, source.1
        );
        for (root, rule) in &self.rules {
            writeln!(code, "// {}", rule.name.replace(['\n', '\r'], " ")).unwrap();
            writeln!(code, "{} => {{", opcode(root, source)?).unwrap();
            let mut destinations = BTreeMap::new();
            for (i, &value) in rule.outputs.iter().enumerate() {
                destinations.entry(value).or_insert(i);
            }
            for i in 0..rule.inputs {
                writeln!(code, "let v{i} = ctx.input({i});").unwrap();
            }
            for inst in &rule.insts {
                for &value in &inst.results {
                    if let Some(&result) = destinations.get(&value) {
                        writeln!(code, "let v{value} = ctx.result({result});").unwrap();
                    } else {
                        let reference = match rule.types[value] {
                            TypeRef::Input(i) => format!("ctx.input({i})"),
                            TypeRef::Result(i) => format!("ctx.result({i})"),
                        };
                        writeln!(code, "let ty{value} = ctx.value_type({reference});\nlet v{value} = ctx.temp(ty{value});").unwrap();
                    }
                }
                let values = |ids: &[usize]| {
                    ids.iter()
                        .map(|i| format!("v{i}"))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                writeln!(
                    code,
                    "ctx.emit({}, &[{}], &[{}]);",
                    opcode(&inst.op, target)?,
                    values(&inst.results),
                    values(&inst.inputs)
                )
                .unwrap();
            }
            for (i, &value) in rule.outputs.iter().enumerate() {
                // Final values are defined directly into their requested
                // destination. Only forwarding/duplicated results need binding.
                if value < rule.inputs || destinations[&value] != i {
                    writeln!(code, "ctx.bind({i}, v{value});").unwrap();
                }
            }
            code.push_str("true\n},\n");
        }
        code.push_str("_ => false,\n}\n}\n");
        Ok(code)
    }
}
