//! Verification statements and validator adapters over shared pure expressions.
use super::{
    Definitions, Op, Param, ParamKind, Pattern, Vocabulary,
    expr::{Emitter, Expr, Library},
};
use crate::Error;
use std::collections::BTreeMap;
use std::fmt::Write;

pub(crate) struct Constraint {
    pub condition: Expr,
    pub text: String,
    pub type_only: bool,
    pub offline: bool,
}

pub(crate) fn check_property(
    source: &str,
    name: &str,
    nodes: Vec<crate::syntax::Node>,
    vocabulary: Vocabulary<'_>,
    library: &mut Library,
) -> Result<Vec<Constraint>, Error> {
    let params = [Param {
        moves: false,
        name: "value".into(),
        kind: ParamKind::Property(name.into()),
    }];
    library.verify(source, nodes, &params, None, &BTreeMap::new(), vocabulary)
}
use crate::syntax::{Kind, Node};
pub(crate) fn describe(node: &Node) -> String {
    match &node.kind {
        Kind::Name(name) => name.clone(),
        Kind::Integer(n) => n.to_string(),
        Kind::Try(value) => format!("{}?", describe(value)),
        Kind::Number(n) => n.to_string(),
        Kind::Text(text) => format!("{text:?}"),
        Kind::Unary(op, value) => format!("{op}({})", describe(value)),
        Kind::Binary(op, lhs, rhs) => format!("({} {op} {})", describe(lhs), describe(rhs)),
        Kind::Member(receiver, name) => format!("{}.{name}", describe(receiver)),
        Kind::Method(receiver, name, args) => format!(
            "{}.{name}({})",
            describe(receiver),
            args.iter().map(describe).collect::<Vec<_>>().join(", ")
        ),
        Kind::Call(name, args) => format!(
            "{name}({})",
            args.iter().map(describe).collect::<Vec<_>>().join(", ")
        ),
        Kind::Lambda(name, body) => format!("|{name}| {}", describe(body)),
        _ => "invalid constraint".into(),
    }
}

pub(crate) fn generate(
    defs: &Definitions,
    formats: &[usize],
    alternatives: &[crate::generate::packing::Alternative],
) -> String {
    let mut groups = BTreeMap::<String, Vec<&str>>::new();
    for (op, &format) in defs.ops.iter().zip(formats) {
        let format = &defs.storage.formats[format];
        let body = emit_body(defs, op, format, true);
        groups.entry(body).or_default().push(&op.name);
    }
    let mut out = String::from(
        "// @generated by veloc-opgen. Edit the .ops definitions instead.\nimpl Function {\n    fn validate_constraints(&self, _module: &crate::ModuleData, _inst: Inst, data: &InstView<'_>, _operands: &[Type], _results: &[Type]) -> Result<()> {\n",
    );
    // Layout-specific auxiliary operands have contracts independent of opcode.
    for alternative in alternatives {
        let op = &alternative.op;
        let format = &alternative.format;
        if op.constraints.is_empty() {
            continue;
        }
        let body = emit_body(defs, op, format, false);
        writeln!(
            out,
            "if matches!(data, InstView::{} {{ .. }}) {{ {body} }}",
            format.name
        )
        .unwrap();
    }
    out.push_str("        match data.opcode() {\n");
    for (body, names) in groups {
        let names = names
            .iter()
            .map(|name| format!("Opcode::{name}"))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(
            out,
            "            {names} => {{\n{body}                Ok(())\n            }},"
        )
        .unwrap();
    }
    out.push_str("        }\n    }\n}\n");
    for property in &defs.properties {
        out.push_str(&property_validator(property, &defs.data.rust));
    }
    out
}

fn property_validator(
    property: &crate::model::Property,
    rust: &super::records::RustTypes,
) -> String {
    let mut out = format!(
        "impl {} {{\n/// Validate the property contract declared in defs. Construction does not run this scan.\npub fn validate(self, dfg: &crate::dfg::DataFlowGraph) -> core::result::Result<(), &'static str> {{\nlet _ = dfg;\n",
        rust.qualified(&property.name)
    );
    if property.constraints.iter().any(|c| c.condition.uses_host()) {
        out.push_str("let _host = crate::host::Context::new(dfg);\n");
    }
    for constraint in &property.constraints {
        let emitter = Emitter {
            instruction: false,
            results: "_results",
            result_values: false,
            operand_types: BTreeMap::new(),
            projections: BTreeMap::from([("value".into(), "self".into())]),
            error: Some(format!("{:?}", constraint.text)),
            storage_used: std::cell::Cell::new(false),
            dfg: "dfg",
        };
        writeln!(
            out,
            "if !({}) {{ return Err({}); }}",
            emitter.term(&constraint.condition),
            emitter.error.as_ref().unwrap()
        )
        .unwrap();
    }
    out.push_str("Ok(())\n}\n}\n");
    out
}

fn emit_body(
    defs: &Definitions,
    op: &Op,
    format: &crate::storage::Format,
    type_checks: bool,
) -> String {
    let mut body = String::new();
    let mut storage_used = false;
    for param in &op.params {
        if let ParamKind::Property(ty) = &param.kind
            && defs.properties.iter().any(|p| p.name == *ty)
        {
            let projections = crate::generate::packing::projections(
                op,
                format,
                "&self.dfg",
                |name| {
                    format!(
                        "*_f{}",
                        format.fields.iter().position(|f| f.name == name).unwrap()
                    )
                },
                |v| format!("{v}.expect(\"checked property storage\")"),
            );
            let value = &projections
                .iter()
                .find(|(p, _)| *p == param.name)
                .unwrap()
                .1;
            writeln!(body, "({value}).validate(&self.dfg).map_err(|error| self.constraint_error(_inst, error))?;").unwrap();
            storage_used = true;
        }
    }
    for (index, pattern) in op
        .signature
        .results
        .patterns()
        .unwrap_or_default()
        .iter()
        .enumerate()
    {
        if let Pattern::Property(name, _) = pattern {
            let projections = crate::generate::packing::projections(
                op,
                format,
                "&self.dfg",
                |name| {
                    format!(
                        "*_f{}",
                        format.fields.iter().position(|f| f.name == name).unwrap()
                    )
                },
                |v| format!("{v}.expect(\"checked property storage\")"),
            );
            let value = &projections.iter().find(|(p, _)| p == name).unwrap().1;
            writeln!(body, "if _results[{index}] != ({value}).ty() {{ return Err(self.constraint_error(_inst, {:?})); }}", format!("result {index} must have the type of `{name}`")).unwrap();
            storage_used = true;
        }
    }
    if let Some(source) = &op.signature_source {
        use crate::model::SignatureSource;
        let error = "self.constraint_error(_inst, \"missing function or signature\")";
        let projections: BTreeMap<_, _> = crate::generate::packing::projections(
            op,
            format,
            "&self.dfg",
            |name| {
                format!(
                    "*_f{}",
                    format.fields.iter().position(|f| f.name == name).unwrap()
                )
            },
            |v| format!("{v}.ok_or_else(|| {error})?"),
        )
        .into_iter()
        .collect();
        let id = match source {
            SignatureSource::Function(name) => format!(
                "_module.functions.get({}).ok_or_else(|| {error})?.signature",
                projections[name]
            ),
            SignatureSource::Signature(name) => projections[name].clone(),
            SignatureSource::Value(name) => format!(
                "self.dfg.value_type({}).as_callable().ok_or_else(|| {error})?.0",
                projections[name]
            ),
        };
        let args = &projections[&op
            .params
            .iter()
            .find(|p| p.kind == ParamKind::Values)
            .expect("checked signature arguments")
            .name];
        let args = args.strip_prefix('*').unwrap_or(args);
        writeln!(body, "let signature = _module.signatures.get({id}).ok_or_else(|| {error})?;\nself.validate_values({:?}, \"value\", {args}, signature.params().iter().copied())?;\nself.validate_values({:?}, \"result\", self.dfg.inst_results(_inst), signature.returns().iter().copied())?;", op.mnemonic, op.mnemonic).unwrap();
        storage_used = true;
    }
    // table(cases, default) requires a default in its physical sequence.
    for (field, binding) in op.bindings() {
        if matches!(binding, crate::model::Binding::Table { .. }) {
            let index = format.fields.iter().position(|f| f.name == *field).unwrap();
            writeln!(body, "if _f{index}.is_empty() {{ return Err(self.constraint_error(_inst, \"branch table must contain a default destination\")); }}").unwrap();
            storage_used = true;
        }
    }
    if op.constraints.iter().any(|c| c.condition.uses_host()) {
        body.push_str("let _host = crate::host::Context::new(&self.dfg).with_module(_module, self.signature);\n");
    }
    for constraint in &op.constraints {
        if constraint.condition.is_bool(true) || (type_checks && constraint.type_only) {
            continue;
        }
        let error = format!("self.constraint_error(_inst, {:?})", constraint.text);
        let projections = crate::generate::packing::projections(
            op,
            format,
            "&self.dfg",
            |name| {
                format!(
                    "*_f{}",
                    format.fields.iter().position(|f| f.name == name).unwrap()
                )
            },
            |value| format!("{value}.ok_or_else(|| {error})?"),
        )
        .into_iter()
        .collect();
        let emitter = Emitter {
            instruction: true,
            results: "_results",
            result_values: false,
            operand_types: op
                .params
                .iter()
                .filter(|p| p.kind == ParamKind::Value)
                .enumerate()
                .map(|(i, p)| (p.name.clone(), format!("_operands[{i}]")))
                .collect(),
            projections,
            error: Some(error),
            storage_used: std::cell::Cell::new(false),
            dfg: "&self.dfg",
        };
        let condition = emitter.term(&constraint.condition);
        storage_used |= emitter.storage_used.get();
        writeln!(
            body,
            "                if !({condition}) {{ return Err({}); }}",
            emitter.error.as_ref().unwrap()
        )
        .unwrap();
    }
    // Type-only predicates use already checked operand/result slices and
    // therefore work for alternate instruction layouts without reprojection.
    if storage_used {
        let fields = format
            .fields
            .iter()
            .enumerate()
            .map(|(i, f)| format!("{}: _f{i}", f.name))
            .collect::<Vec<_>>()
            .join(", ");
        let mismatch = if defs.storage.formats.len() + defs.storage.alternatives.len() == 1 {
            ""
        } else {
            " else { unreachable!(\"checked constraint storage\") }"
        };
        body.insert_str(
            0,
            &format!(
                "                let InstView::{} {{ {fields} }} = data{mismatch};\n",
                format.name
            ),
        );
    }
    body
}
