//! Encoding primitives for trusted, generated bytecode. No IR or VM semantics.
#![no_std]

/// Declare byte opcodes alongside their fixed operand counts and whether a
/// separate u32 failure destination follows. Variable tails belong to the VM.
#[macro_export]
macro_rules! opcodes {
    ($vis:vis enum $enum:ident { $($name:ident($arity:literal, $branch:literal)),* $(,)? }) => {
        #[derive(Clone, Copy, Debug)]
        #[repr(u8)]
        $vis enum $enum { $($name),* }
        impl $enum {
            $vis fn decode(byte: u8) -> Self {
                match byte {
                    $(x if x == Self::$name as u8 => Self::$name,)*
                    _ => panic!("invalid {} opcode {}", stringify!($enum), byte),
                }
            }
            $vis const fn format(self) -> (usize, bool) {
                match self { $(Self::$name => ($arity, $branch),)* }
            }
        }
    };
}

/// Reader for trusted build output. Malformed programs are internal errors.
pub struct Reader<'a> {
    pub bytes: &'a [u8],
    pub pc: usize,
}

impl Reader<'_> {
    #[inline]
    pub fn byte(&mut self) -> u8 {
        let byte = self.bytes[self.pc];
        self.pc += 1;
        byte
    }

    #[inline]
    pub fn u32(&mut self) -> usize {
        let bytes = self.bytes[self.pc..self.pc + 4].try_into().unwrap();
        self.pc += 4;
        u32::from_le_bytes(bytes) as usize
    }

    #[inline]
    pub fn uleb(&mut self) -> usize {
        let mut value = 0u32;
        for shift in (0..35).step_by(7) {
            let byte = self.byte();
            assert!(shift != 28 || byte & 0xf0 == 0, "bytecode index overflow");
            value |= u32::from(byte & 0x7f) << shift;
            if byte & 0x80 == 0 {
                return value as usize;
            }
        }
        unreachable!()
    }

    #[inline]
    pub fn branch(&mut self, success: bool) {
        let failure = self.u32();
        if !success {
            self.pc = failure;
        }
    }
}

pub fn encode_u32(value: usize) -> [u8; 4] {
    u32::try_from(value)
        .expect("bytecode index overflow")
        .to_le_bytes()
}

/// Allocation-free encoding, usable both to measure and to emit an operand.
pub fn encode_uleb(value: usize) -> impl ExactSizeIterator<Item = u8> {
    let mut value = u32::try_from(value).expect("bytecode index overflow");
    let mut bytes = [0; 5];
    let mut len = 0;
    loop {
        let byte = (value & 0x7f) as u8;
        value >>= 7;
        bytes[len] = byte | if value == 0 { 0 } else { 0x80 };
        len += 1;
        if value == 0 {
            return bytes.into_iter().take(len);
        }
    }
}
