//! Rust artifact generation and final formatting.
mod checks;
pub(crate) mod construction;
pub(crate) mod evaluate;
mod operands;
pub(crate) mod ownership;
pub(crate) mod packing;
mod plan;
pub(crate) mod queries;
pub(crate) mod views;
pub use plan::Plan;

use std::fmt::Write;

use crate::model::{Definitions, Op};

const HEADER: &str = "// @generated by veloc-spec. Edit the .spec definitions instead.\n";

fn emit(plan: &Plan, artifact: crate::Emit) -> String {
    use crate::Emit;
    let defs = &plan.definitions;
    match artifact {
        Emit::Types => return crate::types::generate::declarations(&defs.types),
        Emit::Checks => return defs.expressions.method_code() + &checks::generate(defs),
        Emit::Semantics => return crate::semantic::emit::generate(defs),
        _ => {}
    }
    if let plan::Output::Operands(text) = &plan.output {
        let crate::storage::Strategy::Operands(storage) = &defs.storage.strategy else {
            unreachable!()
        };
        return match artifact {
            Emit::Instructions => {
                defs.expressions.method_code()
                    + &crate::model::encoding::generate(&defs.encodings)
                    + &defs.data.generate(
                        &storage.record_names(),
                        crate::model::metadata::record_type(&defs.ops),
                    )
                    + &storage.generate(defs)
                    + &crate::model::metadata::generate(&defs.ops, &storage.opcode, "")
                    + &crate::model::metadata::value_contract(&defs.ops, &storage.opcode, "")
            }
            Emit::TypeRules => {
                let sets = crate::types::generate::Sets::new(defs);
                let mut out = sets.generate();
                out.push_str("mod rules {\nuse super::TypeClass as C;\nuse crate::Type;\n");
                crate::types::rules::generate_validation(
                    defs,
                    &sets,
                    &format!("crate::{}", storage.opcode),
                    &mut out,
                );
                out.push_str("}\n");
                out
            }
            Emit::TextParser | Emit::TextPrinter => {
                crate::text::generate_operands(defs, storage, text, text_output(artifact))
            }
            _ => unreachable!("unsupported operand storage artifact"),
        };
    }
    let plan::Output::Packed(packed) = &plan.output else {
        unreachable!()
    };
    match artifact {
        Emit::TypeRules => {
            let sets = crate::types::generate::Sets::new(defs);
            let mut out = String::from(HEADER);
            out.push_str("use super::TypeClass as C;\nuse crate::Type;\n");
            crate::types::rules::generate_validation(defs, &sets, "crate::Opcode", &mut out);
            out
        }
        Emit::Instructions => {
            let methods = defs.expressions.method_code();
            let query_types = defs.expressions.data_types();
            let mut instructions = defs.data.generate(
                &defs
                    .storage
                    .formats
                    .iter()
                    .filter(|f| !query_types.contains(f.name.as_str()))
                    .map(|f| f.name.clone())
                    .chain(
                        defs.storage
                            .alternatives
                            .iter()
                            .filter(|a| !query_types.contains(a.name.as_str()))
                            .map(|a| a.name.clone()),
                    )
                    .collect::<Vec<_>>(),
                crate::model::metadata::record_type(&defs.ops),
            ) + &defs.storage.instructions();
            instructions.push_str(&methods);
            instructions.push_str(&ownership::generate(defs));
            instructions.push_str(&queries::generate(
                defs,
                queries::Host::Packed(&packed.formats),
            ));
            crate::types::rules::generate_results(defs, &mut instructions);
            instructions
        }
        Emit::Opcodes => {
            let sets = crate::types::generate::Sets::new(defs);
            let mut ops = String::from(HEADER);
            ops.push_str(&defs.storage.format_code());
            ops.push_str(&sets.generate());
            ops.push_str(&crate::model::encoding::generate(&defs.encodings));

            ops.push_str(&opcode_enum(defs, "Opcode"));
            ops.push_str(&crate::model::metadata::value_contract(
                &defs.ops,
                "Opcode",
                "crate::inst::",
            ));
            if let Some(ty) = crate::model::metadata::record_type(&defs.ops) {
                writeln!(ops, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct OpSpec {{ pub mnemonic: &'static str, pub format: OpFormat, pub meta: crate::inst::{ty} }}").unwrap();
                writeln!(ops, "impl Opcode {{ pub const fn meta(self) -> &'static crate::inst::{ty} {{ &self.spec().meta }} }}").unwrap();
                let record = defs.data.records.iter().find(|r| r.name == ty).unwrap();
                if let Some(binding) = &defs.data.rust.analysis {
                    for (method, ty) in [
                        ("traits", &binding.traits),
                        ("memory_effect", &binding.memory),
                    ] {
                        let Some(field) = record.fields.iter().find(|f|
                    matches!(&f.ty, crate::model::records::PropertyType::Named(name) if defs.data.rust.rust(name) == defs.data.rust.rust(ty)))
                    else { continue };
                        writeln!(
                    ops,
                    "impl OpSpec {{ pub const fn {method}(&self) -> {} {{ self.meta.{} }} }}",
                    defs.data.rust.rust(ty),
                    field.name
                )
                .unwrap();
                    }
                }
            }
            ops.push_str("impl Opcode {\n    pub const ALL: &'static [Self] = &[\n");
            for op in &defs.ops {
                writeln!(ops, "        Self::{},", op.name).unwrap();
            }
            ops.push_str(
        "    ];\n    pub const fn spec(self) -> &'static crate::inst::OpSpec {\n        match self {\n",
    );
            for op in &defs.ops {
                writeln!(
            ops,
            "            Self::{} => {{\n                static SPEC: crate::inst::OpSpec = crate::inst::OpSpec {{",
            op.name
        )
        .unwrap();
                writeln!(ops, "                    mnemonic: {:?},", op.mnemonic).unwrap();
                writeln!(
                    ops,
                    "                    format: crate::inst::OpFormat::{},",
                    op.format
                )
                .unwrap();
                writeln!(
                    ops,
                    "                    meta: {},",
                    op.meta.rust("crate::inst::")
                )
                .unwrap();
                ops.push_str("                };\n                &SPEC\n            },\n");
            }
            ops.push_str("        }\n    }\n    pub fn from_mnemonic(mnemonic: &str) -> Option<Self> {\n        match mnemonic {\n");
            for op in &defs.ops {
                writeln!(
                    ops,
                    "            {:?} => Some(Self::{}),",
                    op.mnemonic, op.name
                )
                .unwrap();
            }
            ops.push_str("            _ => None,\n        }\n    }\n}\n");
            ops.push_str(&classification(defs, "has_signature", |op| {
                op.signature_source.is_some()
            }));

            ops
        }
        Emit::Builders => {
            let mut builders = String::from(HEADER);
            builders.push_str("impl<'b, 'a> crate::builder::InstBuilder<'b, 'a> {\n");
            for ((op, &format), builder) in
                defs.ops.iter().zip(&packed.formats).zip(&packed.builders)
            {
                if let Some(builder) = builder {
                    builders.push_str(&packing::builder(
                        op,
                        &defs.storage.formats[format],
                        builder,
                        &defs.data.rust,
                    ));
                }
            }
            builders.push_str("}\n");

            builders
        }
        Emit::Validator => {
            crate::model::constraints::generate(defs, &packed.formats, &packed.alternatives)
        }
        Emit::Evaluation => evaluate::generate(defs, &packed.evaluation),
        Emit::TextParser | Emit::TextPrinter => crate::text::generate(
            defs,
            &packed.formats,
            &packed.alternatives,
            &packed.text,
            text_output(artifact),
        ),
        _ => unreachable!("artifact routed by the generation driver"),
    }
}

/// Classifications depend only on declarations, never on runtime operand data.
fn classification(defs: &Definitions, name: &str, accepts: impl Fn(&Op) -> bool) -> String {
    let ops = defs
        .ops
        .iter()
        .filter(|op| accepts(op))
        .map(|op| format!("Self::{}", op.name))
        .collect::<Vec<_>>();
    let test = if ops.is_empty() {
        "false".into()
    } else if ops.len() == defs.ops.len() {
        "true".into()
    } else {
        format!("matches!(self, {})", ops.join(" | "))
    };
    format!(
        "impl Opcode {{\n/// Definition-derived classification; does not inspect operands.\npub const fn {name}(self) -> bool {{ {test} }}\n}}\n"
    )
}

/// Storage-independent opcode declaration.
pub(crate) fn opcode_enum(defs: &Definitions, name: &str) -> String {
    let mut out = format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n#[allow(non_camel_case_types)]\npub enum {name} {{\n"
    );
    for op in &defs.ops {
        writeln!(out, "{},", op.name).unwrap();
    }
    out.push_str("}\n");
    out
}

fn text_output(artifact: crate::Emit) -> crate::text::Output {
    match artifact {
        crate::Emit::TextParser => crate::text::Output::Parser,
        crate::Emit::TextPrinter => crate::text::Output::Printer,
        _ => unreachable!("not a text artifact"),
    }
}
