//! Rust artifact generation and final formatting.
pub(crate) mod evaluate;
pub(crate) mod packing;
mod plan;
pub use plan::Plan;

use std::fmt::Write;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::Generated;
use crate::model::{Definitions, Op};

const HEADER: &str = "// @generated by veloc-opgen. Edit the .ops definitions instead.\n";

fn generate(plan: &Plan) -> Generated {
    let defs = &plan.definitions;
    let types = crate::types::generate::declarations(&defs.types);
    if let plan::Output::Operands = &plan.output {
        let crate::storage::Strategy::Operands(storage) = &defs.storage.strategy else {
            unreachable!("operand plan matches storage strategy");
        };
        let sets = crate::types::generate::Sets::new(defs);
        let mut type_rules = sets.generate();
        type_rules.push_str("mod rules {\nuse super::TypeClass as C;\nuse crate::Type;\n");
        crate::types::rules::generate_validation(
            defs,
            &sets,
            "crate::GenericOpcode",
            &mut type_rules,
        );
        type_rules.push_str("}\n");
        return Generated {
            types,
            instructions: crate::model::builtins::contracts(&defs.builtins)
                + &defs.data.generate(
                    &storage.record_names(),
                    crate::model::metadata::record_type(&defs.ops),
                )
                + &storage.generate(defs)
                + &crate::model::metadata::generate(&defs.ops, "GenericOpcode", ""),
            type_rules,
            semantics: crate::semantic::emit::generate(defs),
            ..Generated::default()
        };
    }
    let plan::Output::Packed(packed) = &plan.output else {
        unreachable!("operand output already emitted");
    };
    let sets = crate::types::generate::Sets::new(defs);
    let mut type_rules = String::from(HEADER);
    type_rules.push_str("use super::TypeClass as C;\nuse crate::Type;\n");
    let query_types = defs.expressions.data_types();
    let mut instructions = defs.data.generate(
        &defs
            .storage
            .formats
            .iter()
            .filter(|f| !query_types.contains(f.name.as_str()))
            .map(|f| f.name.clone())
            .chain(
                defs.storage
                    .alternatives
                    .iter()
                    .filter(|a| !query_types.contains(a.name.as_str()))
                    .map(|a| a.name.clone()),
            )
            .collect::<Vec<_>>(),
        crate::model::metadata::record_type(&defs.ops),
    ) + &defs.storage.instructions();
    instructions.push_str(&crate::generate::packing::accessors(defs));
    instructions.push_str(&crate::model::ownership::generate(defs));
    instructions.push_str(&crate::model::interfaces::generate(defs, &packed.formats));
    crate::types::rules::generate(defs, &sets, &mut type_rules, &mut instructions);

    let mut ops = String::from(HEADER);
    ops.push_str(&defs.storage.format_code());
    ops.push_str(&sets.generate());
    ops.push_str(&crate::model::builtins::contracts(&defs.builtins));
    for comparison in &defs.comparisons {
        ops.push_str(&comparison.generate());
    }
    ops.push_str(&opcode_enum(defs, "Opcode"));
    if let Some(ty) = crate::model::metadata::record_type(&defs.ops) {
        writeln!(ops, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct OpSpec {{ pub mnemonic: &'static str, pub format: OpFormat, pub meta: crate::inst::{ty} }}").unwrap();
        writeln!(ops, "impl Opcode {{ pub const fn meta(self) -> &'static crate::inst::{ty} {{ &self.spec().meta }} }}").unwrap();
        let record = defs.data.records.iter().find(|r| r.name == ty).unwrap();
        for (method, ty, fallback) in [
            ("traits", "OpTraits", "OpTraits::empty()"),
            (
                "memory_effect",
                "MemoryEffect",
                "crate::inst::MemoryEffect::Unknown",
            ),
        ] {
            let expression = record
                .fields
                .iter()
                .find(|f| f.ty == crate::model::records::PropertyType::Named(ty.into()))
                .map_or_else(|| fallback.to_owned(), |f| format!("self.meta.{}", f.name));
            writeln!(ops, "impl OpSpec {{ pub const fn {method}(&self) -> crate::inst::{ty} {{ {expression} }} }}").unwrap();
        }
    }
    ops.push_str("impl Opcode {\n    pub const ALL: &'static [Self] = &[\n");
    for op in &defs.ops {
        writeln!(ops, "        Self::{},", op.name).unwrap();
    }
    ops.push_str(
        "    ];\n    pub const fn spec(self) -> &'static crate::inst::OpSpec {\n        match self {\n",
    );
    for op in &defs.ops {
        writeln!(
            ops,
            "            Self::{} => {{\n                static SPEC: crate::inst::OpSpec = crate::inst::OpSpec {{",
            op.name
        )
        .unwrap();
        writeln!(ops, "                    mnemonic: {:?},", op.mnemonic).unwrap();
        writeln!(
            ops,
            "                    format: crate::inst::OpFormat::{},",
            op.format
        )
        .unwrap();
        writeln!(
            ops,
            "                    meta: {},",
            op.meta.rust("crate::inst::")
        )
        .unwrap();
        ops.push_str("                };\n                &SPEC\n            },\n");
    }
    ops.push_str("        }\n    }\n    pub fn from_mnemonic(mnemonic: &str) -> Option<Self> {\n        match mnemonic {\n");
    for op in &defs.ops {
        writeln!(
            ops,
            "            {:?} => Some(Self::{}),",
            op.mnemonic, op.name
        )
        .unwrap();
    }
    ops.push_str("            _ => None,\n        }\n    }\n}\n");
    ops.push_str(&classification(defs, "has_signature", |op| {
        op.signature_source.is_some()
    }));
    let mut builders = String::from(HEADER);
    builders.push_str("impl<'b, 'a> crate::builder::InstBuilder<'b, 'a> {\n");
    for ((op, &format), builder) in defs.ops.iter().zip(&packed.formats).zip(&packed.builders) {
        if let Some(builder) = builder {
            builders.push_str(&packing::builder(
                op,
                &defs.storage.formats[format],
                builder,
                &defs.data.rust,
            ));
        }
    }
    builders.push_str("}\n");
    let (text_parser, text_printer) =
        crate::text::generate(defs, &packed.formats, &packed.alternatives, &packed.text);
    Generated {
        types,
        instructions,
        builders,
        text_parser,
        text_printer,
        type_rules,
        host: defs.expressions.host_code(&defs.data.rust),
        validation: crate::model::constraints::generate(
            defs,
            &packed.formats,
            &packed.alternatives,
        ),
        evaluation: evaluate::generate(defs, &packed.evaluation),
        semantics: crate::semantic::emit::generate(defs),
        opcodes: ops,
    }
}

/// Classifications depend only on declarations, never on runtime operand data.
fn classification(defs: &Definitions, name: &str, accepts: impl Fn(&Op) -> bool) -> String {
    let ops = defs
        .ops
        .iter()
        .filter(|op| accepts(op))
        .map(|op| format!("Self::{}", op.name))
        .collect::<Vec<_>>();
    let test = if ops.is_empty() {
        "false".into()
    } else if ops.len() == defs.ops.len() {
        "true".into()
    } else {
        format!("matches!(self, {})", ops.join(" | "))
    };
    format!(
        "impl Opcode {{\n/// Definition-derived classification; does not inspect operands.\npub const fn {name}(self) -> bool {{ {test} }}\n}}\n"
    )
}

/// Storage-independent opcode declaration.
pub(crate) fn opcode_enum(defs: &Definitions, name: &str) -> String {
    let mut out = format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n#[allow(non_camel_case_types)]\npub enum {name} {{\n"
    );
    for op in &defs.ops {
        writeln!(out, "{},", op.name).unwrap();
    }
    out.push_str("}\n");
    out
}

/// Format generated Rust files with the workspace's rustfmt configuration.
///
/// Only the supplied files are formatted; module declarations are not followed.
/// The workspace toolchain includes rustfmt. Missing tools and invalid generated
/// syntax are reported instead of silently leaving unformatted artifacts.
pub fn format_rust(files: &[PathBuf], config: &Path) -> io::Result<()> {
    if files.is_empty() {
        return Ok(());
    }
    let output = Command::new(std::env::var_os("RUSTFMT").unwrap_or_else(|| "rustfmt".into()))
        .arg("--config-path")
        .arg(config.canonicalize()?)
        .args(["--config", "skip_children=true"])
        .args(files)
        .output()
        .map_err(|error| io::Error::new(error.kind(), format!("failed to run rustfmt: {error}")))?;
    if !output.status.success() {
        return Err(io::Error::other(format!(
            "rustfmt failed ({}):\n{}{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        )));
    }
    Ok(())
}
