[package]
name = "veloc-optimizer"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
veloc-bytecode = { workspace = true }
veloc-types = { workspace = true }
veloc-mir = { workspace = true, features = ["std"] }
veloc-analyzer = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
cranelift-entity = { workspace = true }

[build-dependencies]
veloc-spec = { workspace = true }

[dev-dependencies]
veloc-semantics = { workspace = true }
