//! Storage-independent offline semantic artifacts. Consumers bind Opcode and IntCC::
use crate::model::{Definitions, Semantic, SemanticStep};
use std::fmt::Write;
const HEADER: &str = "// @generated by veloc-spec.\n";
pub(crate) fn generate(defs: &Definitions) -> String {
    let mut code = String::from(HEADER);
    code.push_str(
        "/// Offline descriptions; include only in a verification tool or test.\n\
        pub static SPECS: &[veloc_semantics::SemanticSpec<Opcode>] = &[\n",
    );
    for op in &defs.ops {
        if let Some(sem) = &op.semantics {
            writeln!(
                code,
                "veloc_semantics::SemanticSpec {{ opcode: Opcode::{}, program: {} }},",
                op.name,
                semantics(sem)
            )
            .unwrap();
        }
    }
    code.push_str("];\n");
    if defs.ops.iter().any(|op| {
        op.semantics
            .as_ref()
            .is_some_and(|sem| !sem.properties.is_empty())
    }) {
        code.push_str("#[allow(dead_code)] pub fn predicate(cc: IntCC) -> veloc_semantics::IntPredicate { veloc_semantics::IntPredicate::new(cc.is_signed(), cc.outcomes()) }\n");
    }
    code
}

fn semantics(semantics: &Semantic) -> String {
    let steps = semantics
        .steps
        .iter()
        .map(|step| match step {
            SemanticStep::Input(input) => format!("Step::Input({input})"),
            SemanticStep::Const { value, ty } => {
                format!("Step::Const {{ value: BvConst::{value:?}, ty: TypeRef::{ty:?} }}")
            }
            SemanticStep::Apply { op, args } => {
                format!("Step::Apply {{ op: BvOp::{op:?}, args: &{args:?} }}")
            }
            SemanticStep::Compare { kind, lhs, rhs } => {
                let kind = match kind {
                    veloc_semantics::ComparisonRef::Property(i) => {
                        format!("ComparisonRef::Property({i})")
                    }
                    veloc_semantics::ComparisonRef::Fixed(p) => format!(
                        "ComparisonRef::Fixed(IntPredicate::new({}, {}))",
                        p.signed(),
                        p.outcomes()
                    ),
                };
                format!("Step::Compare {{ kind: {kind}, lhs: {lhs}, rhs: {rhs} }}")
            }
            SemanticStep::Convert { kind, arg, to } => format!(
                "Step::Convert {{ kind: Conversion::{kind:?}, arg: {arg}, to: TypeRef::{to:?} }}"
            ),
            SemanticStep::Select { cond, yes, no } => {
                format!("Step::Select {{ cond: {cond}, yes: {yes}, no: {no} }}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let traps = semantics
        .traps
        .iter()
        .map(|(guard, trap)| format!("({guard}, Trap::{trap:?})"))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{{ #[allow(unused_imports)] use veloc_semantics::{{Program, Step, BvConst, BvOp, TypeRef, ComparisonRef, Conversion, IntPredicate, Trap}}; const PROGRAM: Program<'static> = Program {{ inputs: {}, properties: {}, steps: &[{steps}], outputs: &{:?}, traps: &[{traps}] }}; PROGRAM }}",
        semantics.inputs,
        semantics.properties.len(),
        semantics.outputs
    )
}
