[package]
name = "veloc-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
veloc-types = { workspace = true }
veloc = { workspace = true }
veloc-fastjit = { workspace = true }
veloc-mir = { workspace = true }
veloc-optimizer = { workspace = true }
cranelift-entity = { workspace = true }
libc = { workspace = true }
mmap-rs = { workspace = true }
wasmparser = { workspace = true }
wat = { workspace = true, optional = true }
hashbrown = { workspace = true }
elf_loader = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["veloc/std"]
logging = ["dep:env_logger"]
wat = ["dep:wat"]

[dev-dependencies]
wat = { workspace = true }
