//! Typed expression rewrites. This backend emits patterns, not an e-graph or
//! storage-specific matcher. Parsing, imports and templates use the shared AST.
use crate::{
    Definitions, Error,
    syntax::{DeclKind, Kind, Node, Results},
};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

pub(crate) fn generate(
    source: &crate::Source,
    defs: &Definitions,
    dialect: &str,
    opcode: &str,
    types: &str,
) -> Result<String, Error> {
    if !super::identifier(dialect)
        || ![opcode, types]
            .iter()
            .all(|p| p.split("::").all(super::identifier))
    {
        return Err(Error::at(
            source.text(),
            0,
            "invalid equivalence Rust binding",
        ));
    }
    let aliases = source
        .declarations()
        .iter()
        .filter_map(|d| {
            if let DeclKind::TypeSet(n) = &d.kind {
                Some((d.name.clone(), n.clone()))
            } else {
                None
            }
        })
        .collect();
    let operations: BTreeMap<_, _> = defs.operations().map(|op| (op.name.clone(), op)).collect();
    let mut output =
        String::from("// @generated by veloc-spec. Type checking is not an equivalence proof.\n");
    let mut groups: BTreeMap<String, String> = BTreeMap::new();
    for decl in source.declarations() {
        let DeclKind::Rule(sig) = &decl.kind else {
            continue;
        };
        let fail = |message| Error::at(source.text(), decl.offset, message);
        let [generic] = sig.generics.as_slice() else {
            return Err(fail(
                "equivalence rules require one explicit type parameter",
            ));
        };
        if generic.moves || !matches!(&sig.results, Results::Fixed(r) if r.is_empty()) {
            return Err(fail(
                "equivalence rules do not move types or declare return values",
            ));
        }
        let domain =
            super::typed::domain(source.text(), &generic.ty, &aliases, &mut BTreeSet::new())?;
        if domain.is_empty() {
            return Err(fail("empty equivalence type domain"));
        }
        let mut parameters = BTreeMap::new();
        for (i, p) in sig.params.iter().enumerate() {
            if p.moves
                || !matches!(&p.ty.kind, Kind::Name(n) if n == &generic.name)
                || parameters.insert(p.name.clone(), i).is_some()
            {
                return Err(fail(
                    "equivalence parameters must have the declared common type and unique names",
                ));
            }
        }
        for field in decl.fields.keys() {
            if !matches!(field.as_str(), "match" | "emit" | "when") {
                return Err(fail("unknown equivalence rule field"));
            }
        }
        let field = |key: &str| {
            decl.fields
                .get(key)
                .ok_or_else(|| fail("equivalence requires a source and replacement"))
        };
        let mut checker = Checker {
            source: source.text(),
            dialect,
            opcode,
            domain: &domain,
            defs,
            operations: &operations,
            parameters: &parameters,
            bound: BTreeSet::new(),
        };
        let lhs = checker.pattern(field("match")?, true)?;
        if !matches!(&field("match")?.kind, Kind::Call(..)) {
            return Err(fail("equivalence match must be an operation"));
        }
        let rhs = checker.pattern(field("emit")?, false)?;
        let guard = if let Some(node) = decl.fields.get("when") {
            checker.guard(node)?
        } else {
            "None".into()
        };
        let accepted = domain
            .iter()
            .map(|name| {
                let name = name
                    .strip_prefix("Type::")
                    .ok_or_else(|| fail("expected an exact Type constant"))?;
                if defs.type_domain(&format!("Type::{name}")).is_none() {
                    return Err(fail("unknown rule type"));
                }
                Ok(format!("{types}::{name}"))
            })
            .collect::<Result<Vec<_>, Error>>()?
            .join(", ");
        let Kind::Call(root, _) = &field("match")?.kind else {
            unreachable!("checked operation pattern")
        };
        let root = root.strip_prefix(&format!("{dialect}::")).unwrap();
        let rules = groups.entry(root.to_owned()).or_default();
        writeln!(rules, "Rule {{ name: {:?}, types: &[{accepted}], variables: {}, pattern: {lhs}, replacement: {rhs}, guard: {guard} }},", format!("rule at byte {}", decl.offset), parameters.len()).unwrap();
    }
    writeln!(
        output,
        "pub(super) fn rules(opcode: {opcode}) -> &'static [Rule] {{\nmatch opcode {{"
    )
    .unwrap();
    for (root, rules) in groups {
        writeln!(output, "{opcode}::{root} => &[\n{rules}],").unwrap();
    }
    writeln!(output, "_ => &[],\n}}\n}}").unwrap();
    Ok(output)
}

struct Checker<'a> {
    source: &'a str,
    dialect: &'a str,
    opcode: &'a str,
    domain: &'a [String],
    defs: &'a Definitions,
    operations: &'a BTreeMap<String, crate::schema::Operation>,
    parameters: &'a BTreeMap<String, usize>,
    bound: BTreeSet<String>,
}
impl Checker<'_> {
    fn pattern(&mut self, node: &Node, bind: bool) -> Result<String, Error> {
        let fail = |message| Error::at(self.source, node.offset, message);
        match &node.kind {
            Kind::Name(name) => {
                let index = self
                    .parameters
                    .get(name)
                    .ok_or_else(|| fail("undeclared pattern variable"))?;
                if bind {
                    self.bound.insert(name.clone());
                } else if !self.bound.contains(name) {
                    return Err(fail("replacement uses an unmatched variable"));
                }
                Ok(format!("Pattern::Variable({index})"))
            }
            Kind::Number(n) => Ok(format!("Pattern::Constant({n}u64)")),
            Kind::Integer(n) => {
                let bits = u64::try_from(*n)
                    .or_else(|_| i64::try_from(*n).map(|n| n as u64))
                    .map_err(|_| fail("literal exceeds 64 bits"))?;
                Ok(format!("Pattern::Constant({bits}u64)"))
            }
            Kind::Unary("-", n) if matches!(n.kind, Kind::Number(_)) => {
                let Kind::Number(n) = n.kind else {
                    unreachable!()
                };
                Ok(format!("Pattern::Constant({}u64)", (-(n as i64)) as u64))
            }
            Kind::Call(path, args) => {
                let name = path
                    .strip_prefix(&format!("{}::", self.dialect))
                    .ok_or_else(|| fail("unknown equivalence dialect"))?;
                let op = self
                    .operations
                    .get(name)
                    .ok_or_else(|| fail("unknown equivalence operation"))?;
                let sig = op.signature.as_ref().map_err(|e| fail(e.as_str()))?;
                if op.constrained || sig.results.len() != 1 || sig.inputs.len() != args.len() {
                    return Err(fail(
                        "rule operation needs a fixed, unconstrained single-result signature",
                    ));
                }
                let model = self.defs.ops.iter().find(|op| op.name == name).unwrap();
                if model.traits.contains("MAY_TRAP") || model.semantics.is_none() {
                    return Err(fail(
                        "equivalence operation needs non-trapping declared semantics",
                    ));
                }
                for ty in self.domain {
                    let set = self
                        .defs
                        .type_domain(ty)
                        .ok_or_else(|| fail("unknown equivalence type"))?;
                    if !sig
                        .inputs
                        .iter()
                        .chain(&sig.results)
                        .all(|term| set.subset_of(&term.domain))
                    {
                        return Err(fail("operation does not accept every rule type"));
                    }
                }
                let children = args
                    .iter()
                    .map(|n| self.pattern(n, bind))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok(format!(
                    "Pattern::Apply({}::{name}, &[{children}])",
                    self.opcode
                ))
            }
            _ => Err(fail(
                "expected a value, integer literal or qualified operation call",
            )),
        }
    }
    fn guard(&self, node: &Node) -> Result<String, Error> {
        let fail = || {
            Error::at(
                self.source,
                node.offset,
                "guard requires matched_value == integer or matched_value != integer",
            )
        };
        let Kind::Binary(op @ ("==" | "!="), left, right) = &node.kind else {
            return Err(fail());
        };
        let Kind::Name(name) = &left.kind else {
            return Err(fail());
        };
        if !self.bound.contains(name) {
            return Err(fail());
        }
        let Kind::Number(value) = right.kind else {
            return Err(fail());
        };
        Ok(format!(
            "Some(Condition {{ variable: {}, constant: {value}, equal: {} }})",
            self.parameters[name],
            *op == "=="
        ))
    }
}
