//! Typed expression rewrites. This backend emits patterns, not an e-graph or
//! storage-specific matcher. Parsing, imports and templates use the shared AST.
use crate::{
    Definitions, Error,
    syntax::{DeclKind, Kind, Node, Results},
};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use veloc_bytecode::{Reader, Words, equivalence::Instruction as Op};

pub(crate) fn generate(
    source: &crate::Source,
    defs: &Definitions,
    dialect: &str,
    opcode: &str,
    types: &str,
) -> Result<String, Error> {
    if !super::identifier(dialect)
        || ![opcode, types]
            .iter()
            .all(|p| p.split("::").all(super::identifier))
    {
        return Err(Error::at(
            source.text(),
            0,
            "invalid equivalence Rust binding",
        ));
    }
    let aliases = source
        .declarations()
        .iter()
        .filter_map(|d| {
            if let DeclKind::TypeSet(n) = &d.kind {
                Some((d.name.clone(), n.clone()))
            } else {
                None
            }
        })
        .collect();
    let operations: BTreeMap<_, _> = defs.operations().map(|op| (op.name.clone(), op)).collect();
    let mut output =
        String::from("// @generated by veloc-spec. Type checking is not an equivalence proof.\n");
    let mut groups: BTreeMap<String, Vec<CheckedRule>> = BTreeMap::new();
    let mut program = Bytecode::new(defs);
    // Primitive laws and authored rules share checking, query planning and
    // execution. Insert cheap primitive laws first within each opcode group.
    for op in &defs.ops {
        let Some(sem) = &op.semantics else { continue };
        if sem.primitive().is_none()
            || (op.identity.is_none()
                && op.absorbing.is_none()
                && !op.traits.contains("IDEMPOTENT"))
        {
            continue;
        }
        let mut domains = BTreeMap::<_, Vec<String>>::new();
        for instance in &sem.instances {
            let [a, b, result] = instance.kinds.as_slice() else {
                continue;
            };
            if !instance.scalar || instance.error.is_some() || a != b || a != result {
                continue;
            }
            let bits = match a {
                crate::types::Primitive::Int(bits) if *bits <= 64 => *bits,
                crate::types::Primitive::Bool => 1,
                _ => continue,
            };
            let constant = |value: veloc_semantics::BvConst| {
                // Pattern constants are masked to the matched type's width.
                // Share the all-ones rule across widths as with an authored -1.
                if value == veloc_semantics::BvConst::AllOnes {
                    u64::MAX
                } else {
                    value.eval(bits as u16).expect("validated semantic width") as u64
                }
            };
            let scalar = defs.types.scalars.iter().find(|s| s.ty == *a).unwrap();
            let domain = domains
                .entry((op.identity.map(constant), op.absorbing.map(constant)))
                .or_default();
            let ty = format!("Type::{}", scalar.exact());
            if !domain.contains(&ty) {
                domain.push(ty);
            }
        }
        for ((identity, absorbing), domain) in domains {
            let parameters = BTreeMap::from([("x".into(), 0)]);
            let mut checker = Checker {
                source: source.text(),
                dialect,
                domain: &domain,
                defs,
                operations: &operations,
                parameters: &parameters,
                bound: BTreeSet::new(),
            };
            let node = |kind| Node { offset: 0, kind };
            let x = node(Kind::Name("x".into()));
            let mut laws = Vec::new();
            if let Some(value) = identity {
                laws.push(("identity", node(Kind::Integer(value.into())), x.clone()));
            }
            if let Some(value) = absorbing {
                let value = node(Kind::Integer(value.into()));
                laws.push(("absorbing", value.clone(), value));
            }
            if op.traits.contains("IDEMPOTENT") {
                laws.push(("idempotent", x.clone(), x.clone()));
            }
            for (law, rhs_arg, rhs) in laws {
                let lhs = node(Kind::Call(
                    format!("{dialect}::{}", op.name),
                    vec![x.clone(), rhs_arg],
                ));
                let rule = checker.rule(&lhs, &rhs, None, types, &format!("{} {law}", op.name))?;
                groups.entry(op.name.clone()).or_default().push(rule);
            }
        }
    }
    for decl in source.declarations() {
        let DeclKind::Rule(sig) = &decl.kind else {
            continue;
        };
        let fail = |message| Error::at(source.text(), decl.offset, message);
        let [generic] = sig.generics.as_slice() else {
            return Err(fail(
                "equivalence rules require one explicit type parameter",
            ));
        };
        if generic.moves || !matches!(&sig.results, Results::Fixed(r) if r.is_empty()) {
            return Err(fail(
                "equivalence rules do not move types or declare return values",
            ));
        }
        let domain =
            super::typed::domain(source.text(), &generic.ty, &aliases, &mut BTreeSet::new())?;
        if domain.is_empty() {
            return Err(fail("empty equivalence type domain"));
        }
        let mut parameters = BTreeMap::new();
        for (i, p) in sig.params.iter().enumerate() {
            if p.moves
                || !matches!(&p.ty.kind, Kind::Name(n) if n == &generic.name)
                || parameters.insert(p.name.clone(), i).is_some()
            {
                return Err(fail(
                    "equivalence parameters must have the declared common type and unique names",
                ));
            }
        }
        for field in decl.fields.keys() {
            if !matches!(field.as_str(), "match" | "emit" | "when") {
                return Err(fail("unknown equivalence rule field"));
            }
        }
        let field = |key: &str| {
            decl.fields
                .get(key)
                .ok_or_else(|| fail("equivalence requires a source and replacement"))
        };
        let mut checker = Checker {
            source: source.text(),
            dialect,
            domain: &domain,
            defs,
            operations: &operations,
            parameters: &parameters,
            bound: BTreeSet::new(),
        };
        let rule = checker.rule(
            field("match")?,
            field("emit")?,
            decl.fields.get("when"),
            types,
            &format!("rule at byte {}", decl.offset),
        )?;
        let Kind::Call(root, _) = &field("match")?.kind else {
            unreachable!("checked operation pattern")
        };
        let root = root.strip_prefix(&format!("{dialect}::")).unwrap();
        groups.entry(root.to_owned()).or_default().push(rule);
    }
    writeln!(
        output,
        "fn group(opcode: {opcode}) -> Option<Group> {{\nmatch opcode {{"
    )
    .unwrap();
    for (root, rules) in groups {
        let group = program.group(&rules);
        writeln!(output, "{opcode}::{root} => Some(Group {{ {group} }}),").unwrap();
    }
    writeln!(output, "_ => None,\n}}\n}}").unwrap();
    output.push_str(&program.emit(opcode));
    Ok(output)
}

struct CheckedRule {
    lhs: Expr,
    rhs: Expr,
    guard: Option<(usize, u64, bool)>,
    types: String,
    name: String,
}

struct Checker<'a> {
    source: &'a str,
    dialect: &'a str,
    domain: &'a [String],
    defs: &'a Definitions,
    operations: &'a BTreeMap<String, crate::schema::Operation>,
    parameters: &'a BTreeMap<String, usize>,
    bound: BTreeSet<String>,
}
impl Checker<'_> {
    fn rule(
        &mut self,
        lhs: &Node,
        rhs: &Node,
        guard: Option<&Node>,
        types: &str,
        name: &str,
    ) -> Result<CheckedRule, Error> {
        self.bound.clear();
        let lhs_expr = self.pattern(lhs, true)?;
        if !matches!(&lhs.kind, Kind::Call(..)) {
            return Err(Error::at(
                self.source,
                lhs.offset,
                "equivalence match must be an operation",
            ));
        }
        let rhs_expr = self.pattern(rhs, false)?;
        let guard = guard.map(|node| self.guard(node)).transpose()?;
        let accepted = self
            .domain
            .iter()
            .map(|name| {
                let fail = |message| Error::at(self.source, lhs.offset, message);
                let exact = name
                    .strip_prefix("Type::")
                    .ok_or_else(|| fail("expected an exact Type constant"))?;
                if self.defs.type_domain(name).is_none() {
                    return Err(fail("unknown rule type"));
                }
                Ok(format!("{types}::{exact}"))
            })
            .collect::<Result<Vec<_>, Error>>()?
            .join(", ");
        Ok(CheckedRule {
            lhs: lhs_expr,
            rhs: rhs_expr,
            guard,
            types: accepted,
            name: name.to_owned(),
        })
    }

    fn pattern(&mut self, node: &Node, bind: bool) -> Result<Expr, Error> {
        let fail = |message| Error::at(self.source, node.offset, message);
        match &node.kind {
            Kind::Name(name) => {
                let index = self
                    .parameters
                    .get(name)
                    .ok_or_else(|| fail("undeclared pattern variable"))?;
                if bind {
                    self.bound.insert(name.clone());
                } else if !self.bound.contains(name) {
                    return Err(fail("replacement uses an unmatched variable"));
                }
                Ok(Expr::Variable(*index))
            }
            Kind::Number(n) => Ok(Expr::Constant(u64::from(*n))),
            Kind::Integer(n) => {
                let bits = u64::try_from(*n)
                    .or_else(|_| i64::try_from(*n).map(|n| n as u64))
                    .map_err(|_| fail("literal exceeds 64 bits"))?;
                Ok(Expr::Constant(bits))
            }
            Kind::Unary("-", n) if matches!(n.kind, Kind::Number(_)) => {
                let Kind::Number(n) = n.kind else {
                    unreachable!()
                };
                Ok(Expr::Constant((-(n as i64)) as u64))
            }
            Kind::Call(path, args) => {
                let name = path
                    .strip_prefix(&format!("{}::", self.dialect))
                    .ok_or_else(|| fail("unknown equivalence dialect"))?;
                let op = self
                    .operations
                    .get(name)
                    .ok_or_else(|| fail("unknown equivalence operation"))?;
                let sig = op.signature.as_ref().map_err(|e| fail(e.as_str()))?;
                if op.constrained || sig.results.len() != 1 || sig.inputs.len() != args.len() {
                    return Err(fail(
                        "rule operation needs a fixed, unconstrained single-result signature",
                    ));
                }
                let model = self.defs.ops.iter().find(|op| op.name == name).unwrap();
                if model.traits.contains("MAY_TRAP") || model.semantics.is_none() {
                    return Err(fail(
                        "equivalence operation needs non-trapping declared semantics",
                    ));
                }
                for ty in self.domain {
                    let set = self
                        .defs
                        .type_domain(ty)
                        .ok_or_else(|| fail("unknown equivalence type"))?;
                    if !sig
                        .inputs
                        .iter()
                        .chain(&sig.results)
                        .all(|term| set.subset_of(&term.domain))
                    {
                        return Err(fail("operation does not accept every rule type"));
                    }
                }
                let children = args
                    .iter()
                    .map(|n| self.pattern(n, bind))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(Expr::Apply(name.to_owned(), children))
            }
            _ => Err(fail(
                "expected a value, integer literal or qualified operation call",
            )),
        }
    }
    fn guard(&self, node: &Node) -> Result<(usize, u64, bool), Error> {
        let fail = || {
            Error::at(
                self.source,
                node.offset,
                "guard requires matched_value == integer or matched_value != integer",
            )
        };
        let Kind::Binary(op @ ("==" | "!="), left, right) = &node.kind else {
            return Err(fail());
        };
        let Kind::Name(name) = &left.kind else {
            return Err(fail());
        };
        if !self.bound.contains(name) {
            return Err(fail());
        }
        let Kind::Number(value) = right.kind else {
            return Err(fail());
        };
        Ok((self.parameters[name], u64::from(value), *op == "=="))
    }
}

// Only the build-time compiler keeps recursive expressions. Runtime programs
// contain flat instructions with resolved register and backtracking locations.
enum Expr {
    Variable(usize),
    Constant(u64),
    Apply(String, Vec<Expr>),
}

/// Build-time byte assembler. Opcode numbers belong to the runtime enum;
/// operands and branch destinations are little-endian u32 values.
#[derive(Default)]
struct Code {
    bytes: Vec<u8>,
}
impl Code {
    fn emit(&mut self, inst: Op<'_>) -> usize {
        let pc = self.bytes.len();
        inst.encode(&mut self.bytes);
        pc
    }

    fn patch(&mut self, pc: usize, field: &str, value: usize) {
        let inst = Op::read(&mut Reader {
            bytes: &self.bytes,
            pc,
        });
        let offset = pc + inst.field_offset(field).expect("bytecode relocation field");
        self.bytes[offset..offset + 4].copy_from_slice(&veloc_bytecode::encode_u32(value));
    }
}

struct Action {
    entry: usize,
    slots: usize,
    name: String,
    captures: Vec<usize>,
}

#[derive(Clone, PartialEq, Eq)]
enum Step {
    Type(usize),
    Scan {
        source: usize,
        opcode: usize,
        cursor: usize,
        bindings: Vec<Vec<usize>>,
    },
    Same(usize, usize),
    Equal(usize, usize),
    Constant(usize, usize, bool),
    Capture(usize),
}

struct Search {
    step: Step,
    scan: Option<usize>,
    children: Vec<Search>,
}

/// Assign identities on the structured plan, before bytecode layout exists.
fn number_scans(nodes: &mut [Search], next: &mut usize) {
    for node in nodes {
        if matches!(node.step, Step::Scan { .. }) {
            node.scan = Some(*next);
            *next += 1;
        }
        number_scans(&mut node.children, next);
    }
}

/// Prune at generation time; the VM never dispatches on a requested rule.
fn serves(node: &Search, rules: &BTreeSet<usize>) -> bool {
    match node.step {
        Step::Capture(rule) => rules.contains(&rule),
        _ => node.children.iter().any(|child| serves(child, rules)),
    }
}

fn insert_path(nodes: &mut Vec<Search>, steps: &[Step]) {
    let Some((step, rest)) = steps.split_first() else {
        return;
    };
    let index = nodes
        .iter()
        .position(|node| node.step == *step)
        .unwrap_or_else(|| {
            nodes.push(Search {
                step: step.clone(),
                scan: None,
                children: Vec::new(),
            });
            nodes.len() - 1
        });
    insert_path(&mut nodes[index].children, rest);
}

fn collect_vars(expr: &Expr, out: &mut BTreeSet<usize>) {
    match expr {
        Expr::Variable(v) => {
            out.insert(*v);
        }
        Expr::Apply(_, args) => {
            for arg in args {
                collect_vars(arg, out);
            }
        }
        Expr::Constant(_) => {}
    }
}

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord)]
struct Edge {
    opcode: usize,
    columns: Vec<usize>,
}

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord)]
enum Event {
    Added(usize),
    Constant,
    Merged,
}

struct Trigger {
    root: usize,
    // Used only to select a query subtree during generation.
    rules: BTreeSet<usize>,
    entry: usize,
    slot: usize,
    event: Event,
    scan: Option<usize>,
    path: Vec<Edge>,
}

struct Bytecode {
    scans: usize,
    code: Code,
    opcodes: Vec<String>,
    constants: Vec<u64>,
    bindings: Vec<Vec<Vec<usize>>>,
    actions: Vec<Action>,
    triggers: Vec<Trigger>,
    types: Vec<String>,
    slots: usize,
    cursors: usize,
    commutative: BTreeSet<String>,
    input_types: BTreeMap<String, Vec<bool>>,
}

impl Bytecode {
    fn new(defs: &Definitions) -> Self {
        Self {
            scans: 0,
            code: Code::default(),
            opcodes: Vec::new(),
            constants: Vec::new(),
            bindings: Vec::new(),
            actions: Vec::new(),
            triggers: Vec::new(),
            types: Vec::new(),
            slots: 0,
            cursors: 0,
            commutative: defs
                .ops
                .iter()
                .filter(|op| op.traits.contains("COMMUTATIVE"))
                .map(|op| op.name.clone())
                .collect(),
            input_types: defs
                .operations()
                .filter_map(|op| {
                    let sig = op.signature.ok()?;
                    let [result] = sig.results.as_slice() else {
                        return None;
                    };
                    // Only a shared type variable proves equality. Equal domains
                    // alone still permit independently chosen operand types.
                    let inferred = sig
                        .inputs
                        .iter()
                        .map(|input| result.variable.is_some() && input.variable == result.variable)
                        .collect();
                    Some((op.name, inferred))
                })
                .collect(),
        }
    }

    fn group(&mut self, rules: &[CheckedRule]) -> String {
        let entry = self.code.bytes.len();
        let first = self.actions.len();
        let mut tree = Vec::new();
        let (mut slots, mut cursors) = (1, 0);
        for rule in rules {
            self.slots = 1;
            self.cursors = 0;
            let mut vars = BTreeMap::new();
            let ty = crate::bytecode::intern(&mut self.types, rule.types.clone());
            let mut steps = vec![Step::Type(ty)];
            self.pattern(&rule.lhs, 0, &mut vars, &mut steps);
            if let Some((var, value, equal)) = rule.guard {
                let constant = self.constant(value);
                steps.push(Step::Constant(vars[&var], constant, equal));
            }
            let mut captures = BTreeSet::new();
            collect_vars(&rule.rhs, &mut captures);
            let captures: Vec<_> = captures.into_iter().collect();
            let action = self.actions.len();
            self.actions.push(Action {
                entry: 0,
                slots: 0,
                name: rule.name.clone(),
                captures: captures.iter().map(|v| vars[v]).collect(),
            });
            steps.push(Step::Capture(action));
            insert_path(&mut tree, &steps);
            slots = slots.max(self.slots);
            cursors = cursors.max(self.cursors);
        }
        number_scans(&mut tree, &mut self.scans);
        let first_trigger = self.triggers.len();
        self.collect_triggers(&tree, &mut Vec::new());

        // A shared input activates all relevant rules, not one rule task at a
        // time. Exact input identity includes the stable scan and reverse path.
        let mut queries = BTreeMap::new();
        for trigger in self.triggers.drain(first_trigger..) {
            let key = (
                trigger.root,
                trigger.slot,
                trigger.event.clone(),
                trigger.scan,
                trigger.path.clone(),
            );
            queries
                .entry(key)
                .and_modify(|old: &mut Trigger| old.rules.extend(trigger.rules.iter().copied()))
                .or_insert(trigger);
        }
        let mut entries = BTreeMap::new();
        let mut exits = Vec::new();
        for (_, mut trigger) in queries {
            // Different inputs can use the same selected query. Emit it once.
            trigger.entry = if let Some(&entry) = entries.get(&trigger.rules) {
                entry
            } else {
                let entry = self.code.bytes.len();
                exits.extend(self.search(&tree, &trigger.rules));
                entries.insert(trigger.rules.clone(), entry);
                entry
            };
            self.triggers.push(trigger);
        }
        self.patch_exits(exits, self.code.bytes.len());
        self.code.emit(Op::Return {});
        for (offset, rule) in rules.iter().enumerate() {
            self.actions[first + offset].entry = self.code.bytes.len();
            let mut captures = BTreeSet::new();
            collect_vars(&rule.rhs, &mut captures);
            let captures: Vec<_> = captures.into_iter().collect();
            let mut values = captures.len() + 1;
            if let Expr::Constant(value) = rule.rhs {
                let constant = self.constant(value);
                self.code.emit(Op::SetConstant { constant });
            } else {
                let value = self.build(&rule.rhs, &captures, &mut values);
                self.code.emit(Op::Union { value });
            }
            self.code.emit(Op::Return {});
            self.actions[first + offset].slots = values;
        }
        format!("entry: {entry}, slots: {slots}, cursors: {cursors}")
    }

    fn patch_exits(&mut self, exits: Vec<(usize, &'static str)>, target: usize) {
        for (pc, field) in exits {
            self.code.patch(pc, field, target);
        }
    }

    /// Siblings are alternatives, not exclusive cases. Exhaust every child
    /// before advancing its parent scan; failed checks try the next sibling.
    fn search(&mut self, nodes: &[Search], rules: &BTreeSet<usize>) -> Vec<(usize, &'static str)> {
        let mut exits = Vec::new();
        for node in nodes {
            if !serves(node, rules) {
                continue;
            }
            self.patch_exits(exits, self.code.bytes.len());
            exits = Vec::new();
            match &node.step {
                Step::Scan {
                    source,
                    opcode,
                    cursor,
                    bindings,
                } => {
                    let scan = node.scan.expect("numbered scan");
                    let bindings = crate::bytecode::intern(&mut self.bindings, bindings.clone());
                    self.code.emit(Op::OpenScan {
                        scan,
                        cursor: *cursor,
                        source: *source,
                        opcode: *opcode,
                        bindings,
                    });
                    let retry = self.code.bytes.len();
                    let pc = self.code.emit(Op::ScanNext {
                        cursor: *cursor,
                        exhausted: 0,
                    });
                    let children = self.search(&node.children, rules);
                    self.patch_exits(children, retry);
                    exits.push((pc, "exhausted"));
                }
                Step::Capture(rule) => {
                    self.code.emit(Op::Capture { rule: *rule });
                    exits.push((self.code.emit(Op::Jump { target: 0 }), "target"));
                }
                step => {
                    let op = match *step {
                        Step::Type(types) => Op::CheckTypeIn {
                            value: 0,
                            types,
                            otherwise: 0,
                        },
                        Step::Same(lhs, rhs) => Op::CheckSameType {
                            lhs,
                            rhs,
                            otherwise: 0,
                        },
                        Step::Equal(lhs, rhs) => Op::CheckEqual {
                            lhs,
                            rhs,
                            otherwise: 0,
                        },
                        Step::Constant(value, constant, true) => Op::CheckConstantEq {
                            value,
                            constant,
                            otherwise: 0,
                        },
                        Step::Constant(value, constant, false) => Op::CheckConstantNe {
                            value,
                            constant,
                            otherwise: 0,
                        },
                        _ => unreachable!(),
                    };
                    exits.push((self.code.emit(op), "otherwise"));
                    exits.extend(self.search(&node.children, rules));
                }
            }
        }
        exits
    }

    fn collect_triggers(&mut self, nodes: &[Search], prefix: &mut Vec<(Step, usize)>) {
        for node in nodes {
            if let Step::Capture(rule) = node.step {
                self.triggers_for(rule, prefix);
            } else {
                prefix.push((node.step.clone(), node.scan.unwrap_or(0)));
                self.collect_triggers(&node.children, prefix);
                prefix.pop();
            }
        }
    }

    /// Derive wake-up entries and operand indexes from the exact scan plan
    /// that emitted the matcher, not a second traversal of the source pattern.
    fn triggers_for(&mut self, rule: usize, prefix: &[(Step, usize)]) {
        let mut paths: BTreeMap<usize, Vec<Edge>> = BTreeMap::from([(0, Vec::new())]);
        let mut root = None;
        for (step, scan) in prefix {
            if let Step::Scan {
                source,
                opcode,
                bindings,
                ..
            } = step
            {
                root.get_or_insert(*opcode);
                let parent = paths[source].clone();
                self.triggers.push(Trigger {
                    root: root.unwrap(),
                    rules: BTreeSet::from([rule]),
                    entry: 0,
                    slot: *source,
                    event: Event::Added(*opcode),
                    scan: Some(*scan),
                    path: parent.clone(),
                });
                let slots = &bindings[0];
                for &slot in slots {
                    // Canonical argument sorting may swap physical columns,
                    // even for a symmetric pattern that needs only one binding.
                    let columns =
                        if self.commutative.contains(&self.opcodes[*opcode]) && slots.len() == 2 {
                            vec![0, 1]
                        } else {
                            bindings
                                .iter()
                                .flat_map(|binding| binding.iter().enumerate())
                                .filter_map(|(i, &s)| (s == slot).then_some(i))
                                .collect::<BTreeSet<_>>()
                                .into_iter()
                                .collect()
                        };
                    let mut path = vec![Edge {
                        opcode: *opcode,
                        columns,
                    }];
                    path.extend(parent.clone());
                    paths.insert(slot, path);
                }
            }
        }
        let root = root.expect("rule root scan");
        let constants: BTreeSet<_> = prefix
            .iter()
            .filter_map(|(step, _)| {
                if let Step::Constant(slot, _, _) = step {
                    Some(*slot)
                } else {
                    None
                }
            })
            .collect();
        for (slot, path) in paths {
            if constants.contains(&slot) {
                self.triggers.push(Trigger {
                    root,
                    rules: BTreeSet::from([rule]),
                    entry: 0,
                    slot,
                    event: Event::Constant,
                    scan: None,
                    path: path.clone(),
                });
            }
            // Unions can create new joins and satisfy repeated-variable checks
            // without adding any expression. Every bound class is a dependency.
            self.triggers.push(Trigger {
                root,
                rules: BTreeSet::from([rule]),
                entry: 0,
                slot,
                event: Event::Merged,
                scan: None,
                path,
            });
        }
    }

    fn emit(&self, opcode: &str) -> String {
        let opcodes = self
            .opcodes
            .iter()
            .map(|op| format!("{opcode}::{op}"))
            .collect::<Vec<_>>()
            .join(", ");
        let mut output = String::new();
        let mut code = String::new();
        let mut reader = Reader {
            bytes: &self.code.bytes,
            pc: 0,
        };
        while reader.pc < reader.bytes.len() {
            let start = reader.pc;
            let inst = Op::read(&mut reader);
            writeln!(code, "\n        // @{start:04x} {inst:?}").unwrap();
            for byte in &reader.bytes[start..reader.pc] {
                write!(code, "{byte}, ").unwrap();
            }
        }
        let types = self
            .types
            .iter()
            .map(|t| format!("&[{t}]"))
            .collect::<Vec<_>>()
            .join(", ");
        let bindings = self
            .bindings
            .iter()
            .enumerate()
            .map(|(id, bindings)| {
                let rows = bindings
                    .iter()
                    .map(|slots| format!("&{slots:?}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("        /* {id} */ &[{rows}],")
            })
            .collect::<Vec<_>>()
            .join("\n");
        let actions = self
            .actions
            .iter()
            .map(|action| {
                format!(
                    "Rule {{ entry: {}, slots: {}, name: {:?}, captures: &{:?} }}",
                    action.entry, action.slots, action.name, action.captures
                )
            })
            .collect::<Vec<_>>()
            .join(",\n");
        writeln!(output, "#[rustfmt::skip]\nstatic PROGRAM: Program = Program {{\n    types: &[{types}],\n    rules: &[{actions}],\n    opcodes: &[{opcodes}],\n    constants: &{:?},\n    bindings: &[\n{bindings}\n    ],\n    code: &[{}\n],\n}};",
            self.constants, code).unwrap();
        writeln!(output, "static TRIGGERS: &[Trigger] = &[").unwrap();
        let mut added: BTreeMap<usize, Vec<usize>> = BTreeMap::new();
        let mut constants = Vec::new();
        let mut merged = Vec::new();
        let mut indexes: BTreeMap<usize, BTreeSet<usize>> = BTreeMap::new();
        for (id, trigger) in self.triggers.iter().enumerate() {
            match trigger.event {
                Event::Added(op) => added.entry(op).or_default().push(id),
                Event::Constant => constants.push(id),
                Event::Merged => merged.push(id),
            }
            let path = trigger
                .path
                .iter()
                .map(|edge| {
                    indexes
                        .entry(edge.opcode)
                        .or_default()
                        .extend(&edge.columns);
                    format!(
                        "Edge {{ opcode: {opcode}::{}, columns: &{:?} }}",
                        self.opcodes[edge.opcode], edge.columns
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(output, "Trigger {{ root: {opcode}::{}, entry: {}, slot: {}, scan: {:?}, path: &[{path}] }},",
                self.opcodes[trigger.root], trigger.entry, trigger.slot, trigger.scan).unwrap();
        }
        writeln!(output, "];").unwrap();
        writeln!(
            output,
            "pub(super) fn added(op: {opcode}) -> &'static [usize] {{ match op {{"
        )
        .unwrap();
        for (op, ids) in added {
            writeln!(output, "{opcode}::{} => &{:?},", self.opcodes[op], ids).unwrap();
        }
        writeln!(output, "_ => &[], }} }}").unwrap();
        writeln!(
            output,
            "pub(super) const CONSTANT_TRIGGERS: &[usize] = &{constants:?};"
        )
        .unwrap();
        writeln!(
            output,
            "pub(super) const MERGE_TRIGGERS: &[usize] = &{merged:?};"
        )
        .unwrap();
        writeln!(
            output,
            "pub(super) fn indexed_columns(op: {opcode}) -> &'static [usize] {{ match op {{"
        )
        .unwrap();
        for (op, columns) in indexes {
            let columns: Vec<_> = columns.into_iter().collect();
            writeln!(output, "{opcode}::{} => &{:?},", self.opcodes[op], columns).unwrap();
        }
        writeln!(output, "_ => &[], }} }}").unwrap();
        output
    }

    fn constant(&mut self, value: u64) -> usize {
        crate::bytecode::intern(&mut self.constants, value)
    }

    fn opcode(&mut self, name: &str) -> usize {
        crate::bytecode::intern(&mut self.opcodes, name.to_owned())
    }

    fn slot(&mut self) -> usize {
        let slot = self.slots;
        self.slots += 1;
        slot
    }

    /// Slots follow structural traversal, independent of source variable names.
    /// Ancestor bindings are never overwritten by descendant alternatives.
    fn pattern(
        &mut self,
        expr: &Expr,
        source: usize,
        vars: &mut BTreeMap<usize, usize>,
        steps: &mut Vec<Step>,
    ) {
        let Expr::Apply(op, args) = expr else {
            unreachable!("operation pattern")
        };
        let cursor = self.cursors;
        self.cursors += 1;
        let opcode = self.opcode(op);
        let symmetric = match args.as_slice() {
            [Expr::Variable(a), Expr::Variable(b)] => a == b,
            [Expr::Constant(a), Expr::Constant(b)] => a == b,
            _ => false,
        };
        let commutative = args.len() == 2 && self.commutative.contains(op) && !symmetric;
        let slots: Vec<_> = args.iter().map(|_| self.slot()).collect();
        let mut bindings = vec![slots.clone()];
        if commutative {
            bindings.push(slots.iter().rev().copied().collect());
        }
        steps.push(Step::Scan {
            source,
            opcode,
            cursor,
            bindings,
        });
        let mut children = Vec::new();
        for (column, (arg, &slot)) in args.iter().zip(&slots).enumerate() {
            let inferred = &self.input_types[op];
            let same = if commutative {
                inferred.iter().all(|&same| same)
            } else {
                inferred[column]
            };
            if !same {
                steps.push(Step::Same(slot, source));
            }
            match arg {
                Expr::Variable(v) => {
                    if let Some(&previous) = vars.get(v) {
                        steps.push(Step::Equal(previous, slot));
                    } else {
                        vars.insert(*v, slot);
                    }
                }
                Expr::Constant(value) => {
                    let constant = self.constant(*value);
                    steps.push(Step::Constant(slot, constant, true));
                }
                Expr::Apply(..) => children.push((arg, slot)),
            }
        }
        for (child, slot) in children {
            self.pattern(child, slot, vars, steps);
        }
    }

    fn build(&mut self, expr: &Expr, captures: &[usize], values: &mut usize) -> usize {
        match expr {
            Expr::Variable(v) => {
                return captures.binary_search(v).expect("captured RHS variable") + 1;
            }
            Expr::Constant(value) => {
                let constant = self.constant(*value);
                self.code.emit(Op::Constant {
                    dst: *values,
                    constant,
                });
            }
            Expr::Apply(op, args) => {
                let args: Vec<_> = args
                    .iter()
                    .map(|arg| self.build(arg, captures, values))
                    .collect();
                let opcode = self.opcode(op);
                self.code.emit(Op::Build {
                    dst: *values,
                    opcode,
                    args: Words::Values(&args),
                });
            }
        }
        let slot = *values;
        *values += 1;
        slot
    }
}
