//! MIR projections of the checked builtin vocabulary.

use std::fmt::Write;

use crate::builtins::{Builtins, Flags};

const HEADER: &str = "// @generated by veloc-opgen; edit defs/builtins.ops.\n";

pub(crate) fn contracts(defs: &Builtins) -> String {
    let mut out = HEADER.to_owned();
    for (name, layout) in &defs.encodings {
        out.push_str(&layout.generate(name));
    }
    for (name, set) in &defs.flags {
        flags(&mut out, name, set);
    }
    out.push_str("impl MemoryEffect {\n");
    for (name, effect) in &defs.effects {
        writeln!(
            out,
            "pub const {name}: Self = Self::new(MemoryRegions({}), MemoryRegions({}));",
            effect.reads, effect.writes
        )
        .unwrap();
    }
    out.push_str("}\n");
    out
}

fn flags(out: &mut String, ty: &str, flags: &Flags) {
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct {ty}({});",
        flags.storage.name()
    )
    .unwrap();
    writeln!(out, "impl {ty} {{").unwrap();
    writeln!(
        out,
        "pub const NONE: Self = Self(0);\npub const ALL: Self = Self({});",
        flags.all()
    )
    .unwrap();
    out.push_str("pub const fn empty() -> Self { Self::NONE }\npub const fn is_empty(self) -> bool { self.0 == 0 }\npub const fn union(self, other: Self) -> Self { Self(self.0 | other.0) }\npub const fn contains(self, other: Self) -> bool { self.0 & other.0 == other.0 }\npub const fn intersects(self, other: Self) -> bool { self.0 & other.0 != 0 }\n");
    for flag in &flags.members {
        writeln!(
            out,
            "pub const {}: Self = Self(1 << {});",
            flag.name, flag.bit
        )
        .unwrap();
    }
    out.push_str("const NAMES: &'static [(Self, &'static str)] = &[\n");
    for flag in &flags.members {
        writeln!(
            out,
            "(Self::{}, {:?}),",
            flag.name,
            flag.name.to_ascii_lowercase().replace('_', "-")
        )
        .unwrap();
    }
    out.push_str("];\n}\n");
    writeln!(out, "impl core::fmt::Display for {ty} {{\nfn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\nif self.is_empty() {{ return f.write_str(\"none\"); }}\nlet mut separator = \"\";\nfor &(flag, name) in Self::NAMES {{\nif self.contains(flag) {{\nf.write_str(separator)?;\nf.write_str(name)?;\nseparator = {:?};\n}}\n}}\nOk(())\n}}\n}}", flags.separator).unwrap();
}
