//! MIR projections of the checked builtin vocabulary.

use std::fmt::Write;

use crate::builtins::{Builtins, Flag};

const HEADER: &str = "// @generated by veloc-opgen; edit defs/builtins.ops.\n";

pub(crate) fn contracts(defs: &Builtins) -> String {
    let mut out = HEADER.to_owned();
    flags(&mut out, "OpTraits", &defs.traits);
    flags(&mut out, "MemoryRegions", &defs.regions);
    writeln!(out, "impl MemoryRegions {{\npub const NONE: Self = Self(0);\npub const ALL: Self = Self({});\n}}", defs.all_regions()).unwrap();
    out.push_str("impl MemoryEffect {\n");
    for (name, effect) in &defs.effects {
        writeln!(
            out,
            "pub const {name}: Self = Self::new(MemoryRegions({}), MemoryRegions({}));",
            effect.reads, effect.writes
        )
        .unwrap();
    }
    out.push_str("}\n");
    out
}

fn flags(out: &mut String, ty: &str, flags: &[Flag]) {
    writeln!(out, "impl {ty} {{").unwrap();
    for flag in flags {
        writeln!(
            out,
            "pub const {}: Self = Self(1 << {});",
            flag.name, flag.bit
        )
        .unwrap();
    }
    out.push_str("const NAMES: &'static [(Self, &'static str)] = &[\n");
    for flag in flags {
        writeln!(
            out,
            "(Self::{}, {:?}),",
            flag.name,
            flag.name.to_ascii_lowercase().replace('_', "-")
        )
        .unwrap();
    }
    out.push_str("];\n}\n");
}
