use std::fmt::Write;

use crate::model::{Definitions, Op};
use crate::{Error, Generated};

const HEADER: &str = "// @generated by veloc-opgen. Edit the .ops definitions instead.\n";

pub(crate) fn generate(defs: &Definitions, source: &str) -> Result<Generated, Error> {
    if let crate::storage::Strategy::Operands(storage) = &defs.storage.strategy {
        for op in &defs.ops {
            if !op.constraints.is_empty()
                || op.text.is_some()
                || op.access.is_some()
                || op.params.iter().any(|p| p.moves)
                || op.control.is_some()
                || op.signature_source.is_some()
            {
                return Err(Error::at(
                    source,
                    op.offset,
                    "operand storage does not yet support structural constraints, text adapters or ownership interfaces",
                ));
            }
        }
        let classes = crate::type_gen::Classes::new(defs);
        let mut type_rules = classes.generate(&defs.types);
        type_rules.push_str("mod rules {\nuse super::TypeClass as C;\nuse crate::Type;\n");
        crate::type_rules::generate_validation(
            defs,
            &classes,
            "crate::GenericOpcode",
            &mut type_rules,
        );
        type_rules.push_str("}\n");
        return Ok(Generated {
            instructions: crate::builtin_gen::contracts(&defs.builtins)
                + &defs.data.generate(
                    &storage.record_names(),
                    crate::metadata::record_type(&defs.ops),
                )
                + &storage.generate(defs)
                + &crate::metadata::generate(&defs.ops, "GenericOpcode", ""),
            type_rules,
            semantics: crate::semantic::emit::generate(defs),
            ..Generated::default()
        });
    }
    let classes = crate::type_gen::Classes::new(defs);
    let mut type_rules = String::from(HEADER);
    type_rules.push_str("use super::TypeClass as C;\nuse crate::Type;\n");
    let mut instructions = defs.data.generate(
        &defs
            .storage
            .formats
            .iter()
            .map(|f| f.name.clone())
            .chain(defs.storage.alternatives.iter().map(|a| a.name.clone()))
            .collect::<Vec<_>>(),
        crate::metadata::record_type(&defs.ops),
    ) + &defs.storage.instructions;
    instructions.push_str(&crate::packing::accessors(defs));
    instructions.push_str(&crate::ownership::generate(defs));
    instructions.push_str(&crate::memory::generate(defs));
    crate::type_rules::generate(defs, &classes, &mut type_rules, &mut instructions);

    let mut ops = String::from(HEADER);
    ops.push_str(&defs.storage.formats_code);
    ops.push_str(&classes.generate(&defs.types));
    ops.push_str(&crate::builtin_gen::contracts(&defs.builtins));
    for comparison in &defs.comparisons {
        ops.push_str(&comparison.generate());
    }
    ops.push_str(&opcode_enum(defs, "Opcode"));
    if let Some(ty) = crate::metadata::record_type(&defs.ops) {
        writeln!(ops, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct OpSpec {{ pub mnemonic: &'static str, pub format: OpFormat, pub meta: crate::inst::{ty} }}").unwrap();
        writeln!(ops, "impl Opcode {{ pub const fn meta(self) -> &'static crate::inst::{ty} {{ &self.spec().meta }} }}").unwrap();
        let record = defs.data.records.iter().find(|r| r.name == ty).unwrap();
        for (method, ty, fallback) in [
            ("traits", "OpTraits", "OpTraits::empty()"),
            (
                "memory_effect",
                "MemoryEffect",
                "crate::inst::MemoryEffect::Unknown",
            ),
        ] {
            let expression = record
                .fields
                .iter()
                .find(|f| f.ty == crate::records::PropertyType::Named(ty.into()))
                .map_or_else(|| fallback.to_owned(), |f| format!("self.meta.{}", f.name));
            writeln!(ops, "impl OpSpec {{ pub const fn {method}(&self) -> crate::inst::{ty} {{ {expression} }} }}").unwrap();
        }
    }
    ops.push_str("impl Opcode {\n    pub const ALL: &'static [Self] = &[\n");
    for op in &defs.ops {
        writeln!(ops, "        Self::{},", op.name).unwrap();
    }
    ops.push_str(
        "    ];\n    pub const fn spec(self) -> &'static crate::inst::OpSpec {\n        match self {\n",
    );
    for op in &defs.ops {
        writeln!(
            ops,
            "            Self::{} => {{\n                static SPEC: crate::inst::OpSpec = crate::inst::OpSpec {{",
            op.name
        )
        .unwrap();
        writeln!(ops, "                    mnemonic: {:?},", op.mnemonic).unwrap();
        writeln!(
            ops,
            "                    format: crate::inst::OpFormat::{},",
            op.format
        )
        .unwrap();
        writeln!(
            ops,
            "                    meta: {},",
            op.meta.rust("crate::inst::")
        )
        .unwrap();
        ops.push_str("                };\n                &SPEC\n            },\n");
    }
    ops.push_str("        }\n    }\n    pub fn from_mnemonic(mnemonic: &str) -> Option<Self> {\n        match mnemonic {\n");
    for op in &defs.ops {
        writeln!(
            ops,
            "            {:?} => Some(Self::{}),",
            op.mnemonic, op.name
        )
        .unwrap();
    }
    ops.push_str("            _ => None,\n        }\n    }\n}\n");
    ops.push_str(&classification(defs, "has_control", |op| {
        op.control.is_some()
    }));
    ops.push_str(&classification(defs, "has_signature", |op| {
        op.signature_source.is_some()
    }));
    let mut builders = String::from(HEADER);
    builders.push_str("impl<'b, 'a> crate::builder::InstBuilder<'b, 'a> {\n");
    for op in &defs.ops {
        let format = defs
            .storage
            .formats
            .iter()
            .find(|f| f.name == op.format)
            .unwrap();
        if let Some(method) = crate::packing::builder(op, format, &defs.storage.records, source)? {
            builders.push_str(&method);
        }
    }
    builders.push_str("}\n");
    let (text_parser, text_printer) = crate::text::generate(defs, source)?;
    Ok(Generated {
        types: defs.encoding.generate() + &crate::type_gen::scalars(&defs.types),
        instructions,
        builders,
        text_parser,
        text_printer,
        type_rules,
        validation: crate::constraints::generate(defs, source)?,
        evaluation: crate::evaluate::generate(defs, source)?,
        semantics: crate::semantic::emit::generate(defs),
        opcodes: ops,
    })
}

/// Classifications depend only on declarations, never on runtime operand data.
fn classification(defs: &Definitions, name: &str, accepts: impl Fn(&Op) -> bool) -> String {
    let ops = defs
        .ops
        .iter()
        .filter(|op| accepts(op))
        .map(|op| format!("Self::{}", op.name))
        .collect::<Vec<_>>();
    let test = if ops.is_empty() {
        "false".into()
    } else if ops.len() == defs.ops.len() {
        "true".into()
    } else {
        format!("matches!(self, {})", ops.join(" | "))
    };
    format!(
        "impl Opcode {{\n/// Definition-derived classification; does not inspect operands.\npub const fn {name}(self) -> bool {{ {test} }}\n}}\n"
    )
}

/// Storage-independent opcode declaration.
pub(crate) fn opcode_enum(defs: &Definitions, name: &str) -> String {
    let mut out = format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n#[allow(non_camel_case_types)]\npub enum {name} {{\n"
    );
    for op in &defs.ops {
        writeln!(out, "{},", op.name).unwrap();
    }
    out.push_str("}\n");
    out
}
