use std::collections::BTreeSet;
use std::fmt::Write;

use crate::model::{
    Binding, Definitions, Op, ParamKind, Pattern, Semantic, SemanticStep, SignatureSource, TypeDef,
};
use crate::storage::FieldType;
use crate::{Error, Generated};

const HEADER: &str = "// @generated by veloc-opgen. Edit the .ops definitions instead.\n";

pub(crate) fn generate(defs: &Definitions, source: &str) -> Result<Generated, Error> {
    let classes = crate::type_gen::Classes::new(defs);
    let mut types = String::from(HEADER);
    types.push_str("use super::TypeClass as C;\nuse crate::Type;\n");
    let mut dispatch = String::new();
    crate::type_rules::generate(defs, &classes, &mut types, &mut dispatch);

    let mut ops = String::from(HEADER);
    for comparison in &defs.comparisons {
        ops.push_str(&comparison.generate());
    }
    ops.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum Opcode {\n");
    for op in &defs.ops {
        writeln!(ops, "    {},", op.name).unwrap();
    }
    ops.push_str("}\nimpl Opcode {\n    pub const ALL: &'static [Self] = &[\n");
    for op in &defs.ops {
        writeln!(ops, "        Self::{},", op.name).unwrap();
    }
    ops.push_str(
        "    ];\n    pub const fn spec(self) -> &'static crate::opspec::OpSpec {\n        match self {\n",
    );
    for op in &defs.ops {
        writeln!(
            ops,
            "            Self::{} => {{\n                static SPEC: crate::opspec::OpSpec = crate::opspec::OpSpec {{",
            op.name
        )
        .unwrap();
        writeln!(ops, "                    mnemonic: {:?},", op.mnemonic).unwrap();
        writeln!(
            ops,
            "                    format: crate::opspec::OpFormat::{},",
            op.format
        )
        .unwrap();
        ops.push_str("                    traits: crate::opspec::OpTraits::empty()");
        for prop in &op.traits {
            write!(ops, ".union(crate::opspec::OpTraits::{prop})").unwrap();
        }
        ops.push_str(",\n");
        writeln!(
            ops,
            "                    memory_effect: crate::opspec::MemoryEffect::{},",
            op.memory
        )
        .unwrap();
        ops.push_str("                };\n                &SPEC\n            },\n");
    }
    ops.push_str("        }\n    }\n    pub fn from_mnemonic(mnemonic: &str) -> Option<Self> {\n        match mnemonic {\n");
    for op in &defs.ops {
        writeln!(
            ops,
            "            {:?} => Some(Self::{}),",
            op.mnemonic, op.name
        )
        .unwrap();
    }
    ops.push_str("            _ => None,\n        }\n    }\n}\n");
    ops.push_str("impl<'b, 'a> crate::builder::InstBuilder<'b, 'a> {\n");
    for op in &defs.ops {
        let format = defs
            .storage
            .formats
            .iter()
            .find(|f| f.name == op.format)
            .unwrap();
        if let Some(method) = builder(op, format, &defs.storage.records, source)? {
            ops.push_str(&method);
        }
    }
    ops.push_str("}\n");
    ops.push_str(&accessors(defs));
    ops.push_str(&dispatch);
    let (text_parser, text_printer) = crate::text::generate(defs, source)?;
    Ok(Generated {
        encoding: defs.encoding.generate(),
        builtins: classes.generate(&defs.types) + &crate::builtin_gen::contracts(&defs.builtins),
        scalars: crate::type_gen::scalars(&defs.types),
        formats: defs.storage.formats_code.clone(),
        instructions: defs.storage.instructions.clone(),
        text_parser,
        text_printer,
        types,
        validation: crate::constraints::generate(defs),
        evaluation: crate::evaluate::generate(defs, source)?,
        semantics: semantic_specs(defs),
        opcodes: ops,
        documentation: crate::documentation::generate(defs, &classes),
    })
}

fn accessors(defs: &Definitions) -> String {
    let mut output = String::from(
        "impl crate::InstructionData {\n    pub fn call_info(&self) -> Option<crate::inst::CallInfo> {\n        match (self.opcode(), self) {\n",
    );
    for op in &defs.ops {
        let Some(source) = &op.signature_source else {
            continue;
        };
        let (source, variant) = match source {
            SignatureSource::Function(name) => (name, "Function"),
            SignatureSource::Signature(name) => (name, "Signature"),
        };
        let args = &op
            .params
            .iter()
            .find(|p| p.kind == ParamKind::Values)
            .unwrap()
            .name;
        let field = |name: &str| {
            op.packing
                .iter()
                .find_map(|(field, binding)| {
                    matches!(binding, Binding::Name(param) if param == name).then_some(field)
                })
                .expect("checked call parameter storage")
        };
        writeln!(output,
            "            (crate::Opcode::{}, crate::InstructionData::{} {{ {}: call_signature, {}: call_args, .. }}) => Some(crate::inst::CallInfo {{ signature: crate::inst::SignatureRef::{variant}(*call_signature), args: *call_args }}),",
            op.name, op.format, field(source), field(args)).unwrap();
    }
    output.push_str("            _ => None,\n        }\n    }\n    /// Visit outgoing block calls in storage order, preserving edge arguments and duplicates.\n    pub fn visit_successors(&self, dfg: &crate::dfg::DataFlowGraph, mut f: impl FnMut(crate::BlockCall)) {\n        match self {\n");
    for format in &defs.storage.formats {
        let edges: Vec<_> = format.fields.iter().filter(|field| {
            matches!(&field.ty, FieldType::Named(ty) if matches!(ty.as_str(), "BlockCall" | "JumpTable"))
        }).collect();
        if edges.is_empty() {
            continue;
        }
        let bindings = edges
            .iter()
            .enumerate()
            .map(|(index, field)| format!("{}: edge{index}", field.name))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "            crate::InstructionData::{} {{ {bindings}, .. }} => {{",
            format.name
        )
        .unwrap();
        for (index, field) in edges.iter().enumerate() {
            if matches!(&field.ty, FieldType::Named(ty) if ty == "JumpTable") {
                writeln!(output, "                for &call in dfg.jump_table_targets(*edge{index}) {{ f(call); }}").unwrap();
            } else {
                writeln!(output, "                f(*edge{index});").unwrap();
            }
        }
        output.push_str("            },\n");
    }
    output.push_str("            _ => {},\n        }\n    }\n}\n");
    output
}

fn semantic_specs(defs: &Definitions) -> String {
    let mut code = String::from(HEADER);
    code.push_str(
        "/// Offline descriptions; include only in a verification tool or test.\n\
        pub static SPECS: &[veloc_semantics::SemanticSpec<veloc_mir::Opcode>] = &[\n",
    );
    for op in &defs.ops {
        if let Some(sem) = &op.semantics {
            writeln!(
                code,
                "veloc_semantics::SemanticSpec {{ opcode: veloc_mir::Opcode::{}, program: {} }},",
                op.name,
                semantics(sem)
            )
            .unwrap();
        }
    }
    code.push_str("];\n");
    if let Some(comparison) = defs.comparisons.iter().find(|c| c.name == "IntCC")
        && let Some(predicates) = comparison.integer_predicates()
    {
        code.push_str("#[allow(dead_code)] pub fn predicate(cc: veloc_mir::IntCC) -> veloc_semantics::IntPredicate { match cc {\n");
        for (name, p) in predicates {
            writeln!(
                code,
                "veloc_mir::IntCC::{name} => veloc_semantics::IntPredicate::new({}, {}),",
                p.signed(),
                p.outcomes()
            )
            .unwrap();
        }
        code.push_str("} }\n");
    }
    code
}

fn semantics(semantics: &Semantic) -> String {
    let steps = semantics
        .steps
        .iter()
        .map(|step| match step {
            SemanticStep::Input(input) => format!("Step::Input({input})"),
            SemanticStep::Const { value, ty } => {
                format!("Step::Const {{ value: BvConst::{value:?}, ty: TypeRef::{ty:?} }}")
            }
            SemanticStep::Apply { op, args } => {
                format!("Step::Apply {{ op: BvOp::{op:?}, args: &{args:?} }}")
            }
            SemanticStep::Compare { kind, lhs, rhs } => {
                let kind = match kind {
                    veloc_semantics::ComparisonRef::Property(i) => {
                        format!("ComparisonRef::Property({i})")
                    }
                    veloc_semantics::ComparisonRef::Fixed(p) => format!(
                        "ComparisonRef::Fixed(IntPredicate::new({}, {}))",
                        p.signed(),
                        p.outcomes()
                    ),
                };
                format!("Step::Compare {{ kind: {kind}, lhs: {lhs}, rhs: {rhs} }}")
            }
            SemanticStep::Convert { kind, arg, to } => format!(
                "Step::Convert {{ kind: Conversion::{kind:?}, arg: {arg}, to: TypeRef::{to:?} }}"
            ),
            SemanticStep::Select { cond, yes, no } => {
                format!("Step::Select {{ cond: {cond}, yes: {yes}, no: {no} }}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let traps = semantics
        .traps
        .iter()
        .map(|(guard, trap)| format!("({guard}, Trap::{trap:?})"))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{{ #[allow(unused_imports)] use veloc_semantics::{{Program, Step, BvConst, BvOp, TypeRef, ComparisonRef, Conversion, IntPredicate, Trap}}; const PROGRAM: Program<'static> = Program {{ inputs: {}, properties: {}, steps: &[{steps}], outputs: &{:?}, traps: &[{traps}] }}; PROGRAM }}",
        semantics.inputs,
        semantics.properties.len(),
        semantics.outputs
    )
}

fn inferred_results(ty: &TypeDef) -> bool {
    let bound: Vec<_> = ty
        .operands
        .patterns()
        .unwrap_or_default()
        .iter()
        .filter_map(|p| match p {
            Pattern::Bind(var, _) => Some(*var),
            _ => None,
        })
        .collect();
    ty.results.patterns().is_some_and(|results| {
        results.iter().all(|p| {
            match p {
        Pattern::Exact(_) => true,
        Pattern::Same(var) | Pattern::Bind(var, _) => bound.contains(var),
        Pattern::ElementOf(var) => ty.operands.patterns().unwrap_or_default().iter().any(|p| {
            matches!(p, Pattern::Bind(bound, class) if var == bound && class.shapes() & 1 == 0)
        }),
        _ => false,
    }
        })
    })
}

fn builder(
    op: &Op,
    format: &crate::storage::Format,
    records: &[crate::records::RecordDef],
    source: &str,
) -> Result<Option<String>, Error> {
    let fail = |message| Error::at(source, op.offset, message);
    let ty = &op.signature;
    let Some(results) = ty.results.patterns() else {
        // Signature- and context-selected results need the module's help.
        return Ok(None);
    };
    if op.params.iter().any(|param| {
        matches!(
            param.kind,
            ParamKind::Values | ParamKind::Successor | ParamKind::Successors
        )
    }) {
        return Ok(None);
    }
    let name = op.method_name();
    crate::model::identifier(source, op.offset, &name)?;
    if matches!(
        name.as_str(),
        "block"
            | "builder"
            | "param"
            | "params"
            | "value_type"
            | "push"
            | "push_raw"
            | "push_with_type"
            | "result_pair"
    ) {
        return Err(fail(format!(
            "operation `{}` conflicts with an InstBuilder method",
            op.mnemonic
        )));
    }
    let typed = !inferred_results(ty);
    let mut names = BTreeSet::new();
    if typed {
        names.insert("ty".to_owned());
    }
    let mut params = String::from("&mut self");
    let mut add_param = |name: String, ty: &str| -> Result<(), Error> {
        if !names.insert(name.clone()) {
            return Err(fail(format!("conflicting generated parameter `{name}`")));
        }
        write!(params, ", {name}: {ty}").unwrap();
        Ok(())
    };
    for param in &op.params {
        let ty = match &param.kind {
            ParamKind::Value => "crate::Value".to_owned(),
            ParamKind::Property(ty) if ty == "Bytes" => "alloc::vec::Vec<u8>".into(),
            ParamKind::Property(ty) if records.iter().any(|record| record.name == *ty) => {
                format!("crate::inst::{ty}")
            }
            ParamKind::Property(ty) => FieldType::Named(ty.clone()).qualified_type(),
            ParamKind::Values | ParamKind::Successor | ParamKind::Successors => {
                unreachable!("contextual builder was excluded")
            }
        };
        add_param(param.name.clone(), &ty)?;
    }
    if typed {
        params.push_str(", ty: crate::Type");
    }
    let constructor =
        crate::packing::constructor(op, format, "self.builder().func_mut().dfg", str::to_owned);
    let (ret, body) = match (results.len(), typed) {
        (0, false) => ("", "self.push(data);"),
        (1, false) => (
            " -> crate::Value",
            "self.push(data).expect(\"generated builder produces one result\")",
        ),
        (1, true) => (" -> crate::Value", "self.push_with_type(data, ty)"),
        (2, false) => (
            " -> (crate::Value, crate::Value)",
            "let inst = self.push_raw(data);\n        self.result_pair(inst)",
        ),
        _ => {
            return Err(fail(
                "field builder requires at most two inferred results or one explicit result".into(),
            ));
        }
    };
    Ok(Some(format!(
        "    /// Build `{}` from its logical parameters.\n    pub fn {name}({params}){ret} {{\n        let data = {constructor};\n        {body}\n    }}\n",
        op.mnemonic
    )))
}
