use std::collections::BTreeSet;
use std::fmt::Write;

use crate::model::{
    Binding, Definitions, Op, ParamKind, Pattern, Semantic, SemanticStep, SignatureSource, Slot,
    TypeDef, TypeList,
};
use crate::storage::FieldType;
use crate::{Error, Generated};

const HEADER: &str = "// @generated by veloc-opgen. Edit the .ops definitions instead.\n";

pub(crate) fn generate(defs: &Definitions, source: &str) -> Result<Generated, Error> {
    let mut types = String::from(HEADER);
    types.push_str("use super::{TypeClass as C, TypeList as L, TypePattern as P, TypeRelation as R, TypeScheme as S, TypeSlot as Slot};\nuse crate::Type;\n");
    for op in &defs.ops {
        let ty = &op.signature;
        types.push_str("#[allow(non_upper_case_globals)]\n");
        writeln!(types, "pub const {}: S = S {{", op.name).unwrap();
        writeln!(types, "    operands: {},", type_list(&ty.operands)).unwrap();
        writeln!(types, "    results: {},", type_list(&ty.results)).unwrap();
        types.push_str("    relations: &[\n");
        for relation in &ty.relations {
            let (variant, lhs, rhs) = match relation.kind.as_str() {
                "wider" => ("Wider", "from", "to"),
                "narrower" => ("Narrower", "from", "to"),
                "same_width_distinct" => ("SameWidthDistinct", "lhs", "rhs"),
                _ => unreachable!("relations have been checked"),
            };
            writeln!(
                types,
                "        R::{variant} {{ {lhs}: {}, {rhs}: {} }},",
                slot(&relation.lhs),
                slot(&relation.rhs)
            )
            .unwrap();
        }
        types.push_str("    ],\n};\n");
    }

    let mut ops = String::from(HEADER);
    ops.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum Opcode {\n");
    for op in &defs.ops {
        writeln!(ops, "    {},", op.name).unwrap();
    }
    ops.push_str("}\nimpl Opcode {\n    pub const ALL: &'static [Self] = &[\n");
    for op in &defs.ops {
        writeln!(ops, "        Self::{},", op.name).unwrap();
    }
    ops.push_str(
        "    ];\n    pub const fn spec(self) -> crate::opspec::OpSpec {\n        match self {\n",
    );
    for op in &defs.ops {
        writeln!(
            ops,
            "            Self::{} => crate::opspec::OpSpec {{",
            op.name
        )
        .unwrap();
        writeln!(ops, "                mnemonic: {:?},", op.mnemonic).unwrap();
        writeln!(
            ops,
            "                format: crate::opspec::OpFormat::{},",
            op.format
        )
        .unwrap();
        writeln!(
            ops,
            "                type_scheme: &crate::opspec::type_schemes::{},",
            op.name
        )
        .unwrap();
        ops.push_str("                traits: crate::opspec::OpTraits::empty()");
        for prop in &op.traits {
            write!(ops, ".union(crate::opspec::OpTraits::{prop})").unwrap();
        }
        ops.push_str(",\n");
        writeln!(
            ops,
            "                memory_effect: crate::opspec::MemoryEffect::{},",
            op.memory
        )
        .unwrap();
        writeln!(
            ops,
            "                constraints: &[{}],",
            op.constraints
                .iter()
                .map(|c| format!("crate::opspec::OpConstraint::{c}"))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
        writeln!(
            ops,
            "                identity: {},",
            algebraic(op.identity.as_deref())
        )
        .unwrap();
        writeln!(
            ops,
            "                absorbing: {},",
            algebraic(op.absorbing.as_deref())
        )
        .unwrap();
        writeln!(
            ops,
            "                semantics: {},",
            semantics(op.semantics.as_ref())
        )
        .unwrap();
        ops.push_str("            },\n");
    }
    ops.push_str("        }\n    }\n    pub fn from_mnemonic(mnemonic: &str) -> Option<Self> {\n        match mnemonic {\n");
    for op in &defs.ops {
        writeln!(
            ops,
            "            {:?} => Some(Self::{}),",
            op.mnemonic, op.name
        )
        .unwrap();
    }
    ops.push_str("            _ => None,\n        }\n    }\n}\n");
    ops.push_str("impl<'b, 'a> crate::builder::InstBuilder<'b, 'a> {\n");
    for op in &defs.ops {
        let format = defs
            .storage
            .formats
            .iter()
            .find(|f| f.name == op.format)
            .unwrap();
        if let Some(method) = builder(op, format, source)? {
            ops.push_str(&method);
        }
    }
    ops.push_str("}\n");
    ops.push_str(&accessors(defs));
    let (text_parser, text_printer) = crate::text::generate(defs, source)?;
    Ok(Generated {
        formats: defs.storage.formats_code.clone(),
        instructions: defs.storage.instructions.clone(),
        text_parser,
        text_printer,
        types,
        opcodes: ops,
    })
}

fn type_list(list: &TypeList) -> String {
    match list {
        TypeList::Variadic(patterns) => format!(
            "L::Variadic(&[{}])",
            patterns.iter().map(pattern).collect::<Vec<_>>().join(", ")
        ),
        TypeList::Signature => "L::Signature".into(),
        TypeList::Fixed(patterns) => format!(
            "L::Fixed(&[{}])",
            patterns.iter().map(pattern).collect::<Vec<_>>().join(", ")
        ),
    }
}

fn pattern(p: &Pattern) -> String {
    match p {
        Pattern::Class(class) => format!("P::Class(C::{class})"),
        Pattern::Exact(ty) => format!("P::Exact(Type::{ty})"),
        Pattern::Bind(var, class) => format!("P::Bind({var}, C::{class})"),
        Pattern::Same(var) => format!("P::Same({var})"),
        Pattern::ElementOf(var) => format!("P::ElementOf({var})"),
        Pattern::VectorOf(var) => format!("P::VectorOf({var})"),
        Pattern::ShapeOf(var, class) => format!("P::ShapeOf({var}, C::{class})"),
    }
}

fn slot(slot: &Slot) -> String {
    format!(
        "Slot::{}({})",
        if slot.result { "Result" } else { "Operand" },
        slot.index
    )
}

fn algebraic(constant: Option<&str>) -> String {
    constant
        .map(|c| format!("Some(crate::opspec::AlgebraicConstant::{c})"))
        .unwrap_or_else(|| "None".into())
}

fn accessors(defs: &Definitions) -> String {
    let mut output = String::from(
        "impl crate::InstructionData {\n    pub fn call_info(&self) -> Option<crate::inst::CallInfo> {\n        match (self.opcode(), self) {\n",
    );
    for op in &defs.ops {
        let Some(source) = &op.signature_source else {
            continue;
        };
        let (source, variant) = match source {
            SignatureSource::Function(name) => (name, "Function"),
            SignatureSource::Signature(name) => (name, "Signature"),
        };
        let args = &op
            .params
            .iter()
            .find(|p| p.kind == ParamKind::Values)
            .unwrap()
            .name;
        let field = |name: &str| {
            op.packing
                .iter()
                .find_map(|(field, binding)| {
                    matches!(binding, Binding::Name(param) if param == name).then_some(field)
                })
                .expect("checked call parameter storage")
        };
        writeln!(output,
            "            (crate::Opcode::{}, crate::InstructionData::{} {{ {}: call_signature, {}: call_args, .. }}) => Some(crate::inst::CallInfo {{ signature: crate::inst::SignatureRef::{variant}(*call_signature), args: *call_args }}),",
            op.name, op.format, field(source), field(args)).unwrap();
    }
    output.push_str("            _ => None,\n        }\n    }\n    /// Visit outgoing block calls in storage order, preserving edge arguments and duplicates.\n    pub fn visit_successors(&self, dfg: &crate::dfg::DataFlowGraph, mut f: impl FnMut(crate::BlockCall)) {\n        match self {\n");
    for format in &defs.storage.formats {
        let edges: Vec<_> = format.fields.iter().filter(|field| {
            matches!(&field.ty, FieldType::Named(ty) if matches!(ty.as_str(), "BlockCall" | "JumpTable"))
        }).collect();
        if edges.is_empty() {
            continue;
        }
        let bindings = edges
            .iter()
            .enumerate()
            .map(|(index, field)| format!("{}: edge{index}", field.name))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "            crate::InstructionData::{} {{ {bindings}, .. }} => {{",
            format.name
        )
        .unwrap();
        for (index, field) in edges.iter().enumerate() {
            if matches!(&field.ty, FieldType::Named(ty) if ty == "JumpTable") {
                writeln!(output, "                for &call in dfg.jump_table_targets(*edge{index}) {{ f(call); }}").unwrap();
            } else {
                writeln!(output, "                f(*edge{index});").unwrap();
            }
        }
        output.push_str("            },\n");
    }
    output.push_str("            _ => {},\n        }\n    }\n}\n");
    output
}

fn semantics(semantics: Option<&Semantic>) -> String {
    let Some(semantics) = semantics else {
        return "None".into();
    };
    let steps = semantics.steps.iter().map(|step| match step {
        SemanticStep::Input(input) => format!("crate::semantics::Step::Input({input})"),
        SemanticStep::Const(value) => {
            format!("crate::semantics::Step::Const(crate::semantics::BvConst::{value:?})")
        }
        SemanticStep::Apply { op, args } => format!(
            "crate::semantics::Step::Apply {{ op: crate::semantics::BvOp::{op:?}, args: &{args:?} }}"
        ),
    }).collect::<Vec<_>>().join(", ");
    format!(
        "Some(crate::semantics::Program {{ inputs: {}, steps: &[{steps}], output: {} }})",
        semantics.inputs, semantics.output
    )
}

fn inferred_results(ty: &TypeDef) -> bool {
    let bound: Vec<_> = ty
        .operands
        .patterns()
        .unwrap_or_default()
        .iter()
        .filter_map(|p| match p {
            Pattern::Bind(var, _) => Some(*var),
            _ => None,
        })
        .collect();
    ty.results.patterns().is_some_and(|results| results.iter().all(|p| match p {
        Pattern::Exact(_) => true,
        Pattern::Same(var) | Pattern::Bind(var, _) => bound.contains(var),
        Pattern::ElementOf(var) => ty.operands.patterns().unwrap_or_default().iter().any(|p| {
            matches!(p, Pattern::Bind(bound, class) if var == bound && matches!(class.as_str(), "Vector" | "IntegerVector"))
        }),
        _ => false,
    }))
}

fn builder(
    op: &Op,
    format: &crate::storage::Format,
    source: &str,
) -> Result<Option<String>, Error> {
    let fail = |message| Error::at(source, op.offset, message);
    let ty = &op.signature;
    if op
        .packing
        .values()
        .any(|binding| matches!(binding, Binding::Pool(_) | Binding::Table { .. }))
    {
        return Ok(None);
    }
    let Some(results) = ty.results.patterns() else {
        // Signature- and context-selected results need the module's help.
        return Ok(None);
    };
    if op.params.iter().any(|param| {
        matches!(
            param.kind,
            ParamKind::Values | ParamKind::Successor | ParamKind::Successors
        )
    }) {
        return Ok(None);
    }
    if format.fields.iter().any(|field| match &field.ty {
        FieldType::List(_) => true,
        FieldType::Named(name) => matches!(
            name.as_str(),
            "ValueList"
                | "BlockCall"
                | "JumpTable"
                | "ConstantPoolId"
                | "PtrIndexImmId"
                | "VectorExtId"
                | "VectorMemExtId"
        ),
        FieldType::Values(_) => false,
    }) {
        // Pools, CFG edges and auxiliary state are managed by contextual helpers.
        return Ok(None);
    }
    let name = op.method_name();
    crate::model::identifier(source, op.offset, &name)?;
    if matches!(
        name.as_str(),
        "block"
            | "builder"
            | "param"
            | "params"
            | "value_type"
            | "push"
            | "push_raw"
            | "push_with_type"
            | "result_pair"
    ) {
        return Err(fail(format!(
            "operation `{}` conflicts with an InstBuilder method",
            op.mnemonic
        )));
    }
    let typed = !inferred_results(ty);
    let mut names = BTreeSet::new();
    if typed {
        names.insert("ty".to_owned());
    }
    let mut params = String::from("&mut self");
    let mut add_param = |name: String, ty: &str| -> Result<(), Error> {
        if !names.insert(name.clone()) {
            return Err(fail(format!("conflicting generated parameter `{name}`")));
        }
        write!(params, ", {name}: {ty}").unwrap();
        Ok(())
    };
    for param in &op.params {
        let ty = match &param.kind {
            ParamKind::Value => "crate::Value".to_owned(),
            ParamKind::Property(ty) => FieldType::Named(ty.clone()).qualified_type(),
            ParamKind::Values | ParamKind::Successor | ParamKind::Successors => {
                unreachable!("contextual builder was excluded")
            }
        };
        add_param(param.name.clone(), &ty)?;
    }
    if typed {
        params.push_str(", ty: crate::Type");
    }
    let constructor =
        crate::packing::constructor(op, format, "self.builder.func_mut().dfg", str::to_owned);
    let (ret, body) = match (results.len(), typed) {
        (0, false) => ("", format!("self.push({constructor});")),
        (1, false) => (
            " -> crate::Value",
            format!("self.push({constructor}).expect(\"generated builder produces one result\")"),
        ),
        (1, true) => (
            " -> crate::Value",
            format!("self.push_with_type({constructor}, ty)"),
        ),
        (2, false) => (
            " -> (crate::Value, crate::Value)",
            format!("let inst = self.push_raw({constructor});\n        self.result_pair(inst)"),
        ),
        _ => {
            return Err(fail(
                "field builder requires at most two inferred results or one explicit result".into(),
            ));
        }
    };
    Ok(Some(format!(
        "    /// Build `{}` from its logical parameters.\n    pub fn {name}({params}){ret} {{\n        {body}\n    }}\n",
        op.mnemonic
    )))
}
