use std::collections::BTreeSet;
use std::fmt::Write;

use crate::model::{Binding, Definitions, Op, ParamKind, Semantic, SemanticStep, SignatureSource};
use crate::storage::FieldType;
use crate::{Error, Generated};

const HEADER: &str = "// @generated by veloc-opgen. Edit the .ops definitions instead.\n";

pub(crate) fn generate(defs: &Definitions, source: &str) -> Result<Generated, Error> {
    let classes = crate::type_gen::Classes::new(defs);
    let mut type_rules = String::from(HEADER);
    type_rules.push_str("use super::TypeClass as C;\nuse crate::Type;\n");
    let mut instructions = defs.storage.instructions.clone();
    instructions.push_str(&accessors(defs));
    crate::type_rules::generate(defs, &classes, &mut type_rules, &mut instructions);

    let mut ops = String::from(HEADER);
    ops.push_str(&defs.storage.formats_code);
    ops.push_str(&classes.generate(&defs.types));
    ops.push_str(&crate::builtin_gen::contracts(&defs.builtins));
    for comparison in &defs.comparisons {
        ops.push_str(&comparison.generate());
    }
    ops.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum Opcode {\n");
    for op in &defs.ops {
        writeln!(ops, "    {},", op.name).unwrap();
    }
    ops.push_str("}\nimpl Opcode {\n    pub const ALL: &'static [Self] = &[\n");
    for op in &defs.ops {
        writeln!(ops, "        Self::{},", op.name).unwrap();
    }
    ops.push_str(
        "    ];\n    pub const fn spec(self) -> &'static crate::inst::OpSpec {\n        match self {\n",
    );
    for op in &defs.ops {
        writeln!(
            ops,
            "            Self::{} => {{\n                static SPEC: crate::inst::OpSpec = crate::inst::OpSpec {{",
            op.name
        )
        .unwrap();
        writeln!(ops, "                    mnemonic: {:?},", op.mnemonic).unwrap();
        writeln!(
            ops,
            "                    format: crate::inst::OpFormat::{},",
            op.format
        )
        .unwrap();
        ops.push_str("                    traits: crate::inst::OpTraits::empty()");
        for prop in &op.traits {
            write!(ops, ".union(crate::inst::OpTraits::{prop})").unwrap();
        }
        ops.push_str(",\n");
        writeln!(
            ops,
            "                    memory_effect: crate::inst::MemoryEffect::{},",
            op.memory
        )
        .unwrap();
        ops.push_str("                };\n                &SPEC\n            },\n");
    }
    ops.push_str("        }\n    }\n    pub fn from_mnemonic(mnemonic: &str) -> Option<Self> {\n        match mnemonic {\n");
    for op in &defs.ops {
        writeln!(
            ops,
            "            {:?} => Some(Self::{}),",
            op.mnemonic, op.name
        )
        .unwrap();
    }
    ops.push_str("            _ => None,\n        }\n    }\n}\n");
    let mut builders = String::from(HEADER);
    builders.push_str("impl<'b, 'a> crate::builder::InstBuilder<'b, 'a> {\n");
    for op in &defs.ops {
        let format = defs
            .storage
            .formats
            .iter()
            .find(|f| f.name == op.format)
            .unwrap();
        if let Some(method) = builder(op, format, &defs.storage.records, source)? {
            builders.push_str(&method);
        }
    }
    builders.push_str("}\n");
    let (text_parser, text_printer) = crate::text::generate(defs, source)?;
    Ok(Generated {
        types: defs.encoding.generate() + &crate::type_gen::scalars(&defs.types),
        instructions,
        builders,
        text_parser,
        text_printer,
        type_rules,
        validation: crate::constraints::generate(defs),
        evaluation: crate::evaluate::generate(defs, source)?,
        semantics: semantic_specs(defs),
        opcodes: ops,
    })
}

fn accessors(defs: &Definitions) -> String {
    let mut output = String::from(
        "impl<'a> crate::InstructionView<'a> {\n    pub fn call_info(&self) -> Option<crate::inst::CallInfo<'a>> {\n        match (self.opcode(), self) {\n",
    );
    for op in &defs.ops {
        let Some(source) = &op.signature_source else {
            continue;
        };
        let (source, variant) = match source {
            SignatureSource::Function(name) => (name, "Function"),
            SignatureSource::Signature(name) => (name, "Signature"),
        };
        let args = &op
            .params
            .iter()
            .find(|p| p.kind == ParamKind::Values)
            .unwrap()
            .name;
        let field = |name: &str| {
            op.packing
                .iter()
                .find_map(|(field, binding)| {
                    matches!(binding, Binding::Name(param) if param == name).then_some(field)
                })
                .expect("checked call parameter storage")
        };
        writeln!(output,
            "            (crate::Opcode::{}, crate::InstructionView::{} {{ {}: call_signature, {}: call_args, .. }}) => Some(crate::inst::CallInfo {{ signature: crate::inst::SignatureRef::{variant}(*call_signature), args: call_args }}),",
            op.name, op.format, field(source), field(args)).unwrap();
    }
    output.push_str("            _ => None,\n        }\n    }\n    /// Visit outgoing block calls in storage order, preserving edge arguments and duplicates.\n    pub fn visit_successors(&self, mut f: impl FnMut(crate::Successor<'a>)) {\n        match self {\n");
    for format in &defs.storage.formats {
        let edges: Vec<_> = format.fields.iter().filter(|field| {
            matches!(&field.ty, FieldType::Named(ty) if matches!(ty.as_str(), "BlockCall" | "JumpTable"))
        }).collect();
        if edges.is_empty() {
            continue;
        }
        let bindings = edges
            .iter()
            .enumerate()
            .map(|(index, field)| format!("{}: edge{index}", field.name))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "            crate::InstructionView::{} {{ {bindings}, .. }} => {{",
            format.name
        )
        .unwrap();
        for (index, field) in edges.iter().enumerate() {
            if matches!(&field.ty, FieldType::Named(ty) if ty == "JumpTable") {
                writeln!(
                    output,
                    "                for call in edge{index}.iter() {{ f(call); }}"
                )
                .unwrap();
            } else {
                writeln!(output, "                f(*edge{index});").unwrap();
            }
        }
        output.push_str("            },\n");
    }
    output.push_str("            _ => {},\n        }\n    }\n}\n");
    output
}

fn semantic_specs(defs: &Definitions) -> String {
    let mut code = String::from(HEADER);
    code.push_str(
        "/// Offline descriptions; include only in a verification tool or test.\n\
        pub static SPECS: &[veloc_semantics::SemanticSpec<veloc_mir::Opcode>] = &[\n",
    );
    for op in &defs.ops {
        if let Some(sem) = &op.semantics {
            writeln!(
                code,
                "veloc_semantics::SemanticSpec {{ opcode: veloc_mir::Opcode::{}, program: {} }},",
                op.name,
                semantics(sem)
            )
            .unwrap();
        }
    }
    code.push_str("];\n");
    if let Some(comparison) = defs.comparisons.iter().find(|c| c.name == "IntCC")
        && let Some(predicates) = comparison.integer_predicates()
    {
        code.push_str("#[allow(dead_code)] pub fn predicate(cc: veloc_mir::IntCC) -> veloc_semantics::IntPredicate { match cc {\n");
        for (name, p) in predicates {
            writeln!(
                code,
                "veloc_mir::IntCC::{name} => veloc_semantics::IntPredicate::new({}, {}),",
                p.signed(),
                p.outcomes()
            )
            .unwrap();
        }
        code.push_str("} }\n");
    }
    code
}

fn semantics(semantics: &Semantic) -> String {
    let steps = semantics
        .steps
        .iter()
        .map(|step| match step {
            SemanticStep::Input(input) => format!("Step::Input({input})"),
            SemanticStep::Const { value, ty } => {
                format!("Step::Const {{ value: BvConst::{value:?}, ty: TypeRef::{ty:?} }}")
            }
            SemanticStep::Apply { op, args } => {
                format!("Step::Apply {{ op: BvOp::{op:?}, args: &{args:?} }}")
            }
            SemanticStep::Compare { kind, lhs, rhs } => {
                let kind = match kind {
                    veloc_semantics::ComparisonRef::Property(i) => {
                        format!("ComparisonRef::Property({i})")
                    }
                    veloc_semantics::ComparisonRef::Fixed(p) => format!(
                        "ComparisonRef::Fixed(IntPredicate::new({}, {}))",
                        p.signed(),
                        p.outcomes()
                    ),
                };
                format!("Step::Compare {{ kind: {kind}, lhs: {lhs}, rhs: {rhs} }}")
            }
            SemanticStep::Convert { kind, arg, to } => format!(
                "Step::Convert {{ kind: Conversion::{kind:?}, arg: {arg}, to: TypeRef::{to:?} }}"
            ),
            SemanticStep::Select { cond, yes, no } => {
                format!("Step::Select {{ cond: {cond}, yes: {yes}, no: {no} }}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let traps = semantics
        .traps
        .iter()
        .map(|(guard, trap)| format!("({guard}, Trap::{trap:?})"))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{{ #[allow(unused_imports)] use veloc_semantics::{{Program, Step, BvConst, BvOp, TypeRef, ComparisonRef, Conversion, IntPredicate, Trap}}; const PROGRAM: Program<'static> = Program {{ inputs: {}, properties: {}, steps: &[{steps}], outputs: &{:?}, traps: &[{traps}] }}; PROGRAM }}",
        semantics.inputs,
        semantics.properties.len(),
        semantics.outputs
    )
}

fn builder(
    op: &Op,
    format: &crate::storage::Format,
    records: &[crate::records::RecordDef],
    source: &str,
) -> Result<Option<String>, Error> {
    let fail = |message| Error::at(source, op.offset, message);
    let ty = &op.signature;
    let Some(results) = ty.results.patterns() else {
        // Signature- and context-selected results need the module's help.
        return Ok(None);
    };
    if op.params.iter().any(|param| {
        matches!(
            param.kind,
            ParamKind::Values | ParamKind::Successor | ParamKind::Successors
        )
    }) {
        return Ok(None);
    }
    let name = op.method_name();
    crate::model::identifier(source, op.offset, &name)?;
    if matches!(
        name.as_str(),
        "block"
            | "builder"
            | "param"
            | "params"
            | "value_type"
            | "emit"
            | "insert_inferred"
            | "insert"
    ) {
        return Err(fail(format!(
            "operation `{}` conflicts with an InstBuilder method",
            op.mnemonic
        )));
    }
    let inferred = crate::type_rules::result_exprs(ty);
    let typed = inferred.is_none();
    if typed && results.len() != 1 {
        return Err(fail(
            "field builder requires exactly one explicit result".into(),
        ));
    }
    let mut names = BTreeSet::new();
    if typed {
        names.insert("ty".to_owned());
    }
    let mut params = String::from("&mut self");
    let mut add_param = |name: String, ty: &str| -> Result<(), Error> {
        if !names.insert(name.clone()) {
            return Err(fail(format!("conflicting generated parameter `{name}`")));
        }
        write!(params, ", {name}: {ty}").unwrap();
        Ok(())
    };
    for param in &op.params {
        let ty = match &param.kind {
            ParamKind::Value => "crate::Value".to_owned(),
            ParamKind::Property(ty) if ty == "Bytes" => "alloc::vec::Vec<u8>".into(),
            ParamKind::Property(ty) if records.iter().any(|record| record.name == *ty) => {
                format!("crate::inst::{ty}")
            }
            ParamKind::Property(ty) => FieldType::Named(ty.clone()).qualified_type(),
            ParamKind::Values | ParamKind::Successor | ParamKind::Successors => {
                unreachable!("contextual builder was excluded")
            }
        };
        add_param(param.name.clone(), &ty)?;
    }
    if typed {
        params.push_str(", ty: crate::Type");
    }
    let constructor =
        crate::packing::constructor(op, format, "self.builder().func_mut().dfg", str::to_owned);
    let result_types = if let Some(inferred) = inferred {
        let operands = op
            .params
            .iter()
            .filter(|p| p.kind == ParamKind::Value)
            .collect::<Vec<_>>();
        inferred.iter().map(|r| match r {
            crate::type_rules::ResultExpr::Exact(ty) => format!("crate::Type::{ty}"),
            crate::type_rules::ResultExpr::Operand(index) => format!("self.value_type({})", operands[*index].name),
            crate::type_rules::ResultExpr::Element(index) => format!("self.value_type({}).as_vector().expect(\"result element type requires a vector operand\").element_type().as_type()", operands[*index].name),
        }).collect::<Vec<_>>().join(", ")
    } else {
        "ty".into()
    };
    let (ret, body) = match results.len() {
        0 => (String::new(), "self.insert(data, &types);".to_owned()),
        1 => (
            " -> crate::Value".to_owned(),
            "let [result] = self.emit(data, types);\n        result".to_owned(),
        ),
        count => {
            let types = vec!["crate::Value"; count].join(", ");
            let names = (0..count)
                .map(|i| format!("result{i}"))
                .collect::<Vec<_>>()
                .join(", ");
            (
                format!(" -> ({types})"),
                format!("let [{names}] = self.emit(data, types);\n        ({names})"),
            )
        }
    };
    Ok(Some(format!(
        "    /// Build `{}` without validating its type contract.\n    pub fn {name}({params}){ret} {{\n        let (data, types) = ({constructor}, [{result_types}]);\n        {body}\n    }}\n",
        op.mnemonic
    )))
}
