//! Runtime projections of checked type definitions and exact type sets.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::model::{Definitions, Pattern, TypeList};
use crate::type_set::TypeSet;
use crate::types::Types;

const HEADER: &str = "// @generated by veloc-opgen; edit defs/types.ops.\n";

pub(crate) fn scalars(types: &Types) -> String {
    let mut out = HEADER.to_owned();
    out.push_str("impl Type {\n");
    for s in &types.scalars {
        writeln!(
            out,
            "pub const {}: Self = Self({} << SCALAR_SHIFT);",
            s.exact(),
            s.code
        )
        .unwrap();
    }
    for (name, index) in &types.aliases {
        writeln!(
            out,
            "pub const {name}: Self = Self::{};",
            types.scalars[*index].exact()
        )
        .unwrap();
    }
    out.push_str("/// Decode a layout-independent scalar code. Zero and undeclared codes are invalid.\npub const fn from_scalar_code(code: u8) -> Option<Self> { match code {\n");
    for s in &types.scalars {
        writeln!(out, "{} => Some(Self::{}),", s.code, s.exact()).unwrap();
    }
    out.push_str("_ => None, } }\n/// Look up a scalar type's name, without vector-shape syntax.\npub fn from_name(name: &str) -> Option<Self> { match name {\n");
    for s in &types.scalars {
        writeln!(
            out,
            "{:?} => Some(Self::{}),",
            s.name.to_ascii_lowercase(),
            s.exact()
        )
        .unwrap();
    }
    out.push_str("_ => None, } }\n/// Logical bits per lane; pointers require a target layout.\npub const fn element_bits(self) -> Option<u32> {\nassert!(self.is_valid(), \"invalid MIR type has no element width\");\nmatch self.element_code() {\n");
    for s in &types.scalars {
        writeln!(out, "{} => {:?},", s.code, s.bits).unwrap();
    }
    out.push_str("_ => unreachable!(), } }\nfn element_name(self, debug: bool) -> &'static str { match self.element_code() {\n");
    for s in &types.scalars {
        writeln!(
            out,
            "{} => if debug {{ {:?} }} else {{ {:?} }},",
            s.code,
            s.name,
            s.name.to_ascii_lowercase()
        )
        .unwrap();
    }
    out.push_str("_ => panic!(\"invalid MIR type has no element name\"), } }\n");
    for v in &types.vectors {
        writeln!(
            out,
            "pub const {}: Self = Self::{}.as_scalar().expect(\"checked scalar definition\").vector({}, {}).expect(\"checked vector definition\").as_type();",
            v.name,
            types.scalars[v.element].exact(),
            v.lanes,
            v.scalable
        )
        .unwrap();
    }
    // Structural legality comes from scalar declarations, not public predicates
    // whose meanings may be changed independently in the DSL.
    out.push_str("const fn can_vectorize(self) -> bool {\n");
    out.push_str(&membership(&types.lanes));
    out.push_str("}\n");
    for (name, set) in &types.predicates {
        writeln!(out, "/// Membership in the `{name}` type set declared in defs/types.ops.\n/// Invalid encodings are never members.\npub const fn {name}(self) -> bool {{").unwrap();
        out.push_str(&membership(set));
        out.push_str("}\n");
    }
    out.push_str("}\n");
    out
}

/// Intern equal sets, independently of spelling, before emitting runtime checks.
pub(crate) struct Classes {
    sets: BTreeMap<TypeSet, usize>,
    names: BTreeMap<TypeSet, String>,
}

impl Classes {
    pub fn new(defs: &Definitions) -> Self {
        let mut sets = BTreeMap::new();
        let mut names = BTreeMap::new();
        for (name, set) in &defs.types.classes {
            let next = sets.len();
            sets.entry(set.clone()).or_insert(next);
            names.entry(set.clone()).or_insert_with(|| name.clone());
        }
        for op in &defs.ops {
            for list in [&op.signature.operands, &op.signature.results] {
                let (TypeList::Fixed(patterns) | TypeList::Variadic(patterns)) = list else {
                    continue;
                };
                for pattern in patterns {
                    if let Pattern::Class(set) | Pattern::Bind(_, set) | Pattern::ShapeOf(_, set) =
                        pattern
                    {
                        let next = sets.len();
                        sets.entry(set.clone()).or_insert(next);
                    }
                }
            }
        }
        Self { sets, names }
    }

    pub fn reference(&self, set: &TypeSet) -> String {
        if let Some(name) = self.names.get(set) {
            format!("C::{name}")
        } else {
            format!("C({})", self.sets[set])
        }
    }

    pub fn generate(&self, types: &Types) -> String {
        let mut out = HEADER.to_owned();
        let repr = if self.sets.len() <= 256 {
            "u8"
        } else if self.sets.len() <= 65536 {
            "u16"
        } else {
            "usize"
        };
        writeln!(out, "/// An interned, checked set of exact scalar and vector types.\n/// The identifier is private and is not a stable serialized encoding.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct TypeClass({repr});\n#[allow(non_upper_case_globals)]\nimpl TypeClass {{").unwrap();
        for (name, set) in &types.classes {
            writeln!(out, "pub const {name}: Self = Self({});", self.sets[set]).unwrap();
        }
        out.push_str("pub fn accepts(self, ty: crate::Type) -> bool {\nif !ty.is_valid() { return false; }\nlet code = ty.element_code();\nlet shape = ty.lane_count().trailing_zeros() + if ty.is_scalable() { 16 } else { 0 };\nlet shapes: u32 = match self.0 {\n");
        for (set, id) in &self.sets {
            writeln!(out, "{id} => {},", shape_match(set, "code")).unwrap();
        }
        out.push_str("_ => unreachable!(\"invalid generated type class\"),\n};\nshapes & (1 << shape) != 0\n} }\n");
        out
    }
}

fn membership(set: &TypeSet) -> String {
    format!(
        "if self.0 & !USED_MASK != 0 {{ return false; }}\nlet shapes: u32 = {};\nlet shape = self.lanes_log2() as u32 + if self.is_scalable() {{ 16 }} else {{ 0 }};\nshapes & (1 << shape) != 0\n",
        shape_match(set, "self.element_code()")
    )
}

/// Both signature constraints and public predicates use the same membership
/// projection; neither depends on another runtime predicate to classify a type.
fn shape_match(set: &TypeSet, code: &str) -> String {
    let mut out = format!("match {code} {{\n");
    let mut masks = BTreeMap::<u32, Vec<u8>>::new();
    for (&code, &shapes) in &set.0 {
        masks.entry(shapes).or_default().push(code);
    }
    for (shapes, codes) in masks {
        let pattern = if codes.len() > 2 && codes.windows(2).all(|pair| pair[1] - pair[0] == 1) {
            format!("{}..={}", codes[0], codes.last().unwrap())
        } else {
            codes
                .iter()
                .map(u8::to_string)
                .collect::<Vec<_>>()
                .join(" | ")
        };
        writeln!(out, "{pattern} => {shapes:#010x},").unwrap();
    }
    out.push_str("_ => 0, }");
    out
}
