//! Runtime projections of checked type definitions and exact type sets.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::model::{Definitions, Pattern, TypeList};
use crate::types::TypeSet;
use crate::types::Types;

const HEADER: &str = "// @generated by veloc-spec; edit defs/types.spec.\n";

pub(crate) fn declarations(types: &Types) -> String {
    let mut out = HEADER.to_owned();
    for scalar in &types.scalars {
        let name = scalar.exact();
        let domain = match scalar.ty {
            crate::types::Primitive::Int(bits) => format!("Int({bits})"),
            crate::types::Primitive::Float(bits) => format!("Float({bits})"),
            crate::types::Primitive::Bool => "Bool".into(),
            crate::types::Primitive::Ptr => "Ptr".into(),
        };
        writeln!(out, "const _: () = assert!(matches!(crate::Type::{name}.as_scalar(), Some(s) if matches!(s.element(), veloc_types::Scalar::{domain})), \"logical scalar declaration disagrees with its Rust representation\");").unwrap();
    }
    for (name, set) in &types.exact {
        if name.starts_with("Type::") {
            continue;
        }
        let (&element, &shapes) = set.0.first_key_value().expect("exact type");
        let scalar = types
            .scalars
            .iter()
            .find(|s| s.ty == element)
            .expect("declared element")
            .exact();
        let shape = shapes.trailing_zeros();
        let value = if shape == 0 {
            format!("crate::Type::{scalar}")
        } else {
            format!(
                "veloc_types::ScalarType::{scalar}.vector({}, {}).expect(\"checked vector definition\").as_type()",
                1u32 << (shape % 16),
                shape >= 16
            )
        };
        writeln!(out, "pub const {name}: crate::Type = {value};").unwrap();
    }
    out
}

/// Intern equal sets, independently of spelling, before emitting runtime checks.
pub(crate) struct Sets {
    sets: BTreeMap<TypeSet, usize>,
    names: BTreeMap<TypeSet, String>,
    descriptions: BTreeMap<TypeSet, String>,
}

impl Sets {
    pub fn new(defs: &Definitions) -> Self {
        let mut sets = BTreeMap::new();
        let mut names = BTreeMap::new();
        for (name, set) in &defs.types.sets {
            names.entry(set.clone()).or_insert_with(|| name.clone());
        }
        for op in &defs.ops {
            for list in [&op.signature.operands, &op.signature.results] {
                let (TypeList::Fixed(patterns) | TypeList::Variadic(patterns)) = list else {
                    continue;
                };
                for pattern in patterns {
                    if let Pattern::Set(set) | Pattern::Bind(_, set) | Pattern::Property(_, set) =
                        pattern
                    {
                        let next = sets.len();
                        sets.entry(set.clone()).or_insert(next);
                    }
                }
            }
        }
        let descriptions = sets
            .keys()
            .map(|set| (set.clone(), describe(set, &defs.types)))
            .collect();
        Self {
            sets,
            names,
            descriptions,
        }
    }

    pub fn describe(&self, set: &TypeSet) -> &str {
        &self.descriptions[set]
    }

    pub fn reference(&self, set: &TypeSet) -> String {
        if let Some(name) = self.names.get(set) {
            format!("C::{name}")
        } else {
            format!("C({})", self.sets[set])
        }
    }

    pub fn generate(&self) -> String {
        let mut out = HEADER.to_owned();
        let repr = if self.sets.len() <= 256 {
            "u8"
        } else if self.sets.len() <= 65536 {
            "u16"
        } else {
            "usize"
        };
        writeln!(out, "/// An interned, checked set of exact scalar and vector types.\n/// The identifier is private and is not a stable serialized encoding.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct TypeClass({repr});\n#[allow(non_upper_case_globals)]\nimpl TypeClass {{").unwrap();
        for (set, name) in &self.names {
            if let Some(id) = self.sets.get(set) {
                writeln!(out, "pub const {name}: Self = Self({id});").unwrap();
            }
        }
        out.push_str("pub fn accepts(self, ty: crate::Type) -> bool {\nlet Some(code) = ty.element() else { return false; };\nlet shape = ty.lane_count().trailing_zeros() + if ty.is_scalable() { 16 } else { 0 };\nlet shapes: u32 = match self.0 {\n");
        for (set, id) in &self.sets {
            writeln!(out, "{id} => {},", shape_match(set, "code")).unwrap();
        }
        out.push_str("_ => unreachable!(\"invalid generated type set\"),\n};\nshapes & (1 << shape) != 0\n} }\n");
        out
    }
}

/// Describe exact sets using named subsets, then explicit remaining shapes.
/// This runs only in the generator; diagnostics carry the resulting string.
fn describe(set: &TypeSet, types: &Types) -> String {
    let mut rest = set.clone();
    let mut parts = Vec::new();
    while let Some((name, subset)) = types
        .sets
        .iter()
        .filter(|(_, subset)| subset.subset_of(&rest))
        .max_by_key(|(_, subset)| subset.0.values().map(|mask| mask.count_ones()).sum::<u32>())
    {
        parts.push(name.clone());
        rest.0.retain(|code, mask| {
            *mask &= !subset.0.get(code).copied().unwrap_or(0);
            *mask != 0
        });
    }
    for (code, shapes) in rest.0 {
        let scalar = types
            .scalars
            .iter()
            .find(|s| s.ty == code)
            .expect("checked scalar code")
            .exact();
        for shape in 0..32 {
            if shapes & (1 << shape) == 0 {
                continue;
            }
            parts.push(match shape {
                0 => scalar.clone(),
                1..=15 => format!("vector({scalar}, {})", 1u32 << shape),
                _ => format!("vector({scalar}, scalable({}))", 1u32 << (shape - 16)),
            });
        }
    }
    parts.join(" | ")
}

/// Emit type-set membership directly from element and shape masks.
fn shape_match(set: &TypeSet, code: &str) -> String {
    let mut out = format!("match {code} {{\n");
    let mut masks = BTreeMap::<u32, Vec<crate::types::Primitive>>::new();
    for (&kind, &shapes) in &set.0 {
        masks.entry(shapes).or_default().push(kind);
    }
    for (shapes, kinds) in masks {
        let pattern = kinds
            .iter()
            .map(|kind| format!("veloc_types::Scalar::{kind:?}"))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(out, "{pattern} => {shapes:#010x},").unwrap();
    }
    out.push_str("_ => 0, }");
    out
}
